gText_ObtainedTheItem::
	.string "Obtém um(a) {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Sua bolsa está cheia…$"

gText_PutItemInPocket::
	.string "{PLAYER} coloca o(a) {STR_VAR_2}\n"
	.string "no {STR_VAR_3} da bolsa.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} encontra um(a) {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Isso é ruim!\n"
	.string "A sua bolsa está cheia…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} coloca o(a) {STR_VAR_2}\n"
	.string "na bolsa.$"

gText_ObtainedTheDecor::
	.string "Obtém um(a) {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Isso é ruim! Näo há mais espaço\n"
	.string "para outro(a) {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "O {STR_VAR_2} foi transferido\n"
	.string "para o seu PC.$"
