gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} foi transferido\n"
	.string "para o PC Público\p"
	.string "Foi colocado\n"
	.string "na “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} foi transferido\p"
	.string "para o PC da Lanette.\n"
	.string "Foi colocado na “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "Box “{STR_VAR_3}” no\n"
	.string "PC Público está cheia.\p"
	.string "{STR_VAR_2} foi transferido\n"
	.string "para a “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "Box “{STR_VAR_3}” no\n"
	.string "PC da Lanette está cheia.\p"
	.string "{STR_VAR_2} foi transferido\n"
	.string "para a “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "Sem mais espaços para Pokémon!\p"
	.string "As Boxes estäo cheias e näo\n"
	.string "poderäo aceitar novos Pokémon!$"

gText_NicknameThisPokemon::
	.string "Você quer dar um apelido\n"
	.string "para {STR_VAR_1}?$"
