gText_WouldYouLikeToRestYourPkmn::
    .string "Olá aventureiro.\n"
    .string "Bem vindo ao Centro Pokémon.\p"
    .string "Posso restaurar a saúde\n"
    .string "dos seus Pokémon?$"

gText_IllTakeYourPkmn::
    .string "Okay, um momento por favor$"

gText_RestoredPkmnToFullHealth::
    .string "Todos os seus Pokémon foram curados.$"

gText_WeHopeToSeeYouAgain::
    .string "Espero revê-lo em breve.$"

gText_WelcomeCutShort::
    .string "Olá e bem vindo\n"
    .string "ao Centro Pokémon.\p"
    .string "Poderei restaurar a vida dos\n"
    .string "seus Pokémon caso permita.\p"
    .string "Você gostaria…$"

gText_NoticesGoldCard::
    .string "Es-este cartäo…\n"
    .string "poderia ser… o Gold Card?!\p"
    .string "A sua cor dourada é linda demais,\n"
    .string "que coisa magn fica, näo acha?\p"
    .string "Já vi varios treinadores com um\n"
    .string "Silver Card antes, mas, {PLAYER},\l"
    .string "você é o primeiro treinador que\l"
    .string "eu vejo com um Gold Card.\p"
    .string "Okay, {PLAYER}, você me concederia\n"
    .string "a honra de curar os seus Pokémon?$"

gText_YouWantTheUsual::
    .string "Estou muito feliz em ver você.\n"
    .string "Deseja o mesmo de sempre?$"

gText_IllTakeYourPkmn2::
    .string "Okay, um momento por favor$"

gText_ThankYouForWaiting::
    .string "Todos os seus Pokémon foram curados.$"

gText_WeHopeToSeeYouAgain2::
    .string "Espero revê-lo em breve.$"
