	.align 2
gText_ConfirmSave::
	.string "Deseja salvar o seu progresso?$"

gText_AlreadySavedFile::
	.string "Já existe um arquivo salvo.\n"
	.string "Deseja sobrescrever o arquivo?$"

gText_SavingDontTurnOff::
	.string "Salvando…\n"
	.string "Aguarde um momento.$"

gText_PlayerSavedGame::
	.string "{PLAYER}, seu progresso foi salvo.$"

gText_DifferentSaveFile::
	.string "!!!!ATENÇÄO!!!!\p"
	.string "Há um arquivo de jogo diferente\n"
	.string "que já está salvo aqui.\p"
	.string "Se você salvar agora, sua aventura,\n"
	.string "incluindo seus itens, Pokémon, etc,\l"
	.string "seräo perdidos.\p"
	.string "Você gostaria de salvar agora e\n"
	.string "substituir o outro arquivo salvo?$"

gText_SaveError::
	.string "Erro ao salvar.\p"
	.string "Por favor, verifique o\n"
	.string "seu save de backup.$"

gText_SavingDontTurnOffPower::
	.string "Salvando…\n"
	.string "Aguarde um momento.$"
