Route102_Text_CalvinIntro:
	.string "Se você tem um Pokémon entäo você\n"
	.string "é um Treinador Oficial Pokémon!\l"
	.string "Você näo pode recusar meu desafio!$"

Route102_Text_CalvinDefeated:
	.string "Arrgh, Eu perdi…\n"
	.string "Eu acho que devo treinar mais…$"

Route102_Text_CalvinPostBattle:
	.string "Poxa! Se você é forte!\n"
	.string "Você poderia ter me falado antes!$"

Route102_Text_CalvinRegister:
	.string "Eu tenho me esforçado muito.\n"
	.string "Eu treino bastante.\p"
	.string "Gostaria de lutar contra você de novo\n"
	.string "anote meu contato na sua Pokénav?$"

Route102_Text_CalvinRegisterShort:
	.string "Gostaria de lutar contra você de novo\n"
	.string "anote meu contato na sua Pokénav?$"

Route102_Text_CalvinRematchIntro:
	.string "Desde que eu perdi para você,\n"
	.string "eu treino meus Pokémon. Você\l"
	.string "näo pode dizer näo ao meu desafio!$"

Route102_Text_CalvinRematchDefeated:
	.string "Ah näo, eu perd…\n"
	.string "O meu treino näo está bom?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Se você ficou forte, eu vou ficar.\n"
	.string "mais forte, também.$"

Route102_Text_AllenIntro:
	.string "Você tornou-se um treinador?\n"
	.string "Entäo somos novatos!$"

Route102_Text_AllenDefeated:
	.string "Eu te chamei porque pensei\n"
	.string "Que poderia ganhar…$"

Route102_Text_AllenPostBattle:
	.string "Eu ainda näo ganhei…\n"
	.string "Eu espero ganhar logo…$"

Route102_Text_RickIntro:
	.string "Oi! Te encontrei!\n"
	.string "Agora te mostro meus Pokémon insetos!$"

Route102_Text_RickDefeated:
	.string "Oh! Perdi feio!$"

Route102_Text_RickPostBattle:
	.string "Se você olhar para um treinador,\n"
	.string "você tem que desafiar! É a regra$"

Route102_Text_TianaIntro:
	.string "Tenho que manter meu objetivo\n"
	.string "ser uma ótima treinadora.\p"
	.string "Ajude-me na minha carreira!$"

Route102_Text_TianaDefeated:
	.string "E o fim de minha linda carreira…$"

Route102_Text_TianaPostBattle:
	.string "Para tentar lutar melhor, eu acho\n"
	.string "que tenho que pegar mais Pokémon.$"

Route103_Text_DaisyIntro:
	.string "Você sentiu uma fragrância\n"
	.string "que atraiu a sua alma?$"

Route103_Text_DaisyDefeated:
	.string "Você foi enganado por esse aroma…$"

Route103_Text_DaisyPostBattle:
	.string "A aromaterapia é uma forma de cura\n"
	.string "que trabalha com as fragâncias.$"

Route103_Text_AmyIntro:
	.string "Amy: Olá! Esta é a minha irmä mais\n"
	.string "nova Liv. Somos uma bela equipe.$"

Route103_Text_AmyDefeated:
	.string "Amy: Oh, tristeza.$"

Route103_Text_AmyPostBattle:
	.string "Amy: Você tem que pensar em tantas\n"
	.string "coisas quando você está lutando\l"
	.string "contra dois treinadores.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "Amy: Uh-oh, tem apenas\n"
	.string "um Pokémon com você.\l"
	.string "Näo pode lutar contra nós assim.$"

Route103_Text_LivIntro:
	.string "Liv: Batalhamos juntas\n"
	.string "como um time.$"

Route103_Text_LivDefeated:
	.string "Liv: Oh… Irmä, perdemos feio…$"

Route103_Text_LivPostBattle:
	.string "Liv: Juntas somos perfeitas,\n"
	.string "eu e minha irmä…\p"
	.string "Näo importa se perdemos…$"

Route103_Text_AmyLivRegister:
	.string "Liv: Acredite, estamos melhores…\n"
	.string "É sério! Vamos uma revache depois?!?$"

Route103_Text_LivNotEnoughPokemon:
	.string "Liv: Se quer lutar contra nós,\n"
	.string "você deve ter 2 Pokémon!\l"
	.string "Näo é justo, se você näo tem!$"

Route103_Text_AmyRematchIntro:
	.string "Amy: Eu sou Amy.\n"
	.string "E esta é a minha irmäzinha Liv.\l"
	.string "Lutamos juntas!$"

Route103_Text_AmyRematchDefeated:
	.string "Amy: Aaaaah, näo!\n"
	.string "Perdemos outra vez…$"

Route103_Text_AmyRematchPostBattle:
	.string "Amy: Você tem que pensar em tantas\n"
	.string "coisas quando você está lutando\l"
	.string "contra dois treinadores.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "Amy: Uh-oh, tem apenas\n"
	.string "um Pokémon com você.\l"
	.string "Näo pode lutar contra nós assim.$"

Route103_Text_LivRematchIntro:
	.string "Liv: Lutamos juntos como uma\n"
	.string "equipe.$"

Route103_Text_LivRematchDefeated:
	.string "Liv: Aaaaaah, perdemos de novo…\n"
	.string "Irmä…$"

Route103_Text_LivRematchPostBattle:
	.string "Liv: Lutamos perfeitamente juntas,\n"
	.string "eu e minha irmä…\p"
	.string "Mas por que perdemos de novo?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Liv: Se quer lutar contra nós,\n"
	.string "você deve ter 2 Pokémon!\l"
	.string "Näo é justo, se você näo tem!$"

Route103_Text_AndrewIntro:
	.string "Minha linha de pesca está embolada.\n"
	.string "Estou täo irritado!\l"
	.string "Näo importa! Quero batalhar$"

Route103_Text_AndrewDefeated:
	.string "Perdi!\n"
	.string "Fiquei ainda mais irritado agora!$"

Route103_Text_AndrewPostBattle:
	.string "Eu ainda estou fervendo de raiva…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "O meu Pokémon é muito adorável.\n"
	.string "Näo tenha medo - eu te mostro!$"

Route103_Text_MiguelDefeated:
	.string "Poxa!\n"
	.string "Era o meu melhor Pokémon.$"

Route103_Text_MiguelPostBattle:
	.string "Veja… O meu Pokémon é täo lindo\n"
	.string "e adorável mesmo desmaiado.$"

Route103_Text_MiguelRegister:
	.string "Eu vou convidar você para conhecer\n"
	.string "meus adoráveis Pokémon novamente.$"

Route103_Text_MiguelRematchIntro:
	.string "Ei, você! Meu lindo e adorável\n"
	.string "Pokémon tornou-se mais adoráviel!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "Adorável Pokémon!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Se eu gastar mais tempo com meu\n"
	.string "Pokémon mais adorável ele se torna.$"

Route103_Text_PeteIntro:
	.string "Hm… Nessa distância…\n"
	.string "Você deveria apenas nadar!$"

Route103_Text_PeteDefeated:
	.string "Ah, eu perdi o rumo!$"

Route103_Text_PetePostBattle:
	.string "Sua pressa\n"
	.string "Oh, eu entendo você agora.\p"
	.string "Se eu tivesse um Pokémon fiel,\n"
	.string "eu queria surfar sobre ele, também!$"

Route103_Text_IsabelleIntro:
	.string "Olhe por onde você anda\n"
	.string "Opa! Nós vamos bater! $"

Route103_Text_IsabelleDefeated:
	.string "Poxa…$"

Route103_Text_IsabellePostBattle:
	.string "Eu sou uma pobre nadadora praticando…\n"
	.string "Oh… Desculpe por quase bater em você.$"

Route103_Text_RhettIntro:
	.string "Uau! Como você entrou\n"
	.string "nesse espaço pequeno?$"

Route103_Text_RhettDefeated:
	.string "Nossa!\n"
	.string "Que sufoco aqui!$"

Route103_Text_RhettPostBattle:
	.string "Gosta de lugares apertados  \n"
	.string "como este?$"

Route103_Text_MarcosIntro:
	.string "O som da minha guitarra\n"
	.string "atraiu você?$"

Route103_Text_MarcosDefeated:
	.string "Meu show solitário acabou…$"

Route103_Text_MarcosPostBattle:
	.string "Eu estava tocando minha guitarra\n"
	.string "e todos estavam ao meu redor.\l"
	.string "Incrível isso… Talvez eu devesse\p"
	.string "ser um profissional.$"

Route104_Text_GinaIntro:
	.string "Gina: Vamos batalhar com nossos\n"
	.string "Pokémon!$"

Route104_Text_GinaDefeat:
	.string "Gina: Perder me irrita!$"

Route104_Text_GinaPostBattle:
	.string "Gina: Você é forte.\n"
	.string "Temos quer treinar bem mais!$"

Route104_Text_GinaNotEnoughMons:
	.string "Gina: Ah? Apenas 1 Pokémon?\n"
	.string "Entäo, nós näo lutaremos com você.\p"
	.string "Se há apenas 1 Pokémon, ele vai ser\n"
	.string "solitário. Isso näo é bom.$"

Route104_Text_MiaIntro:
	.string "Mia: Somos gêmeas, lutaremos\n"
	.string "com Pokémon juntas!$"

Route104_Text_MiaDefeat:
	.string "Mia: Batalhamos juntas, mas nós\n"
	.string "perdemos…$"

Route104_Text_MiaPostBattle:
	.string "Mia: Vamos treinar nossos Pokémon  \n"
	.string "para ficar mais fortes.$"

Route104_Text_MiaNotEnoughMons:
	.string "Mia: Você quer lutar com a gente?\p"
	.string "É um grande NÄO!\n"
	.string "Você näo tem 2 Pokémon com você.\l"
	.string "Estamos muito forte para você!$"

Route104_Text_IvanIntro:
	.string "Porque manter segredo?\n"
	.string "Sou um bom Treinador Pokémon!\p"
	.string "Huh?\n"
	.string "Você me conhece?$"

Route104_Text_IvanDefeat:
	.string "Eu pensei que eu näo era täo ruim,\n"
	.string "mas eu acho que sou sim…$"

Route104_Text_IvanPostBattle:
	.string "Eu gosto muito de pescar.\n"
	.string "Mas acho que vou treinar Pokémon…$"

Route104_Text_BillyIntro:
	.string "Deixar pegadas na areia é täo divertido!$"

Route104_Text_BillyDefeat:
	.string "Ohhh! Eu tenho areia nos meus sapatos!\n"
	.string "Muita areia!$"

Route104_Text_BillyPostBattle:
	.string "Eu quero deixar minhas pegadas\n"
	.string "aqui na areia…\l"
	.string "Mas elas desaparecem rapidamente…$"

Route104_Text_HaleyIntro:
	.string "Se eu… deveria?\n"
	.string "Ou näo…\p"
	.string "Certo, certo, eu vou lutar.$"

Route104_Text_HaleyDefeat:
	.string "Eu näo devia ter lutado…$"

Route104_Text_HaleyPostBattle:
	.string "Se você se depara com uma decisäo e\n"
	.string "deixar que alguém escolha por você,\l"
	.string "você vai se arrepender, assim eu penso.$"

Route104_Text_HaleyRegister1:
	.string "Você é forte, mas devo registrar\n"
	.string "você na minha Pokénav?\l"
	.string "Talvez eu näo…\p"
	.string "Ok, com certeza, vou registrar você!$"

Route104_Text_HaleyRegister2:
	.string "Você é forte, mas devo registrar\n"
	.string "você na minha Pokénav?\l"
	.string "Talvez eu näo…\p"
	.string "Ok, com certeza, vou registrar você!$"

Route104_Text_HaleyRematchIntro:
	.string "Qual é, vamos batalhar!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "Pensei que eu poderia ganhar…$"

Route104_Text_HaleyPostRematch:
	.string "Foi eu quem decidiu batalha, entäo\n"
	.string "aceito essa derrota com muita graça.\p"
	.string "Ainda estou chateado por perder!$"

Route104_Text_WinstonIntro:
	.string "Ah, bom, eu vou aceitar o desafio. \n"
	.string "Eu tenho muito dinheiro.$"

Route104_Text_WinstonDefeat:
	.string "Poxa! Porque eu näo ganhei?$"

Route104_Text_WinstonPostBattle:
	.string "Há coisas que o dinheiro näo compra.\n"
	.string "Tipo os Pokémon…$"

Route104_Text_WinstonRegister1:
	.string "Ei? Você tem uma Pokénav.\n"
	.string "Terei prazer em registrar você.\p"
	.string "Sou rico, eu tenho muito dinheiro.$"

Route104_Text_WinstonRegister2:
	.string "Ei? Você tem uma Pokénav.\n"
	.string "Terei prazer em registrar você.\p"
	.string "Sou rico, eu tenho muito dinheiro.$"

Route104_Text_WinstonRematchIntro:
	.string "Depois que eu perdi, eu aprendi\n"
	.string "muitas coisas sobre os Pokémon.$"

Route104_Text_WinstonRematchDefeat:
	.string "Perdi de novo?\n"
	.string "Por que näo ganho?$"

Route104_Text_WinstonPostRematch:
	.string "Estou fabulosamente rico, mas eu näo\n"
	.string "consigo ganhar uma…\p"
	.string "É täo profundo, o mundo dos Pokémon…$"

Route104_Text_CindyIntro:
	.string "Temos um destino a cumprir!\n"
	.string "Topa termos uma batalha rápida?$"

Route104_Text_CindyDefeat:
	.string "Perdi!$"

Route104_Text_CindyPostBattle:
	.string "Nossa! Assim näo dá para ganhar\n"
	.string "Espero te ver novamente.$"

Route104_Text_CindyRegister1:
	.string "Olá, nos encontramos de novo.\p"
	.string "Que bom! Vamos registrar nossos\n"
	.string "contatos na nossas Pokénavs.$"

Route104_Text_CindyRegister2:
	.string "Olá, nos encontramos de novo.\p"
	.string "Que bom! Vamos registrar nossos\n"
	.string "contatos na nossas Pokénavs.$"
	
Route104_Text_CindyRematchIntro:
	.string "Oi, nos vemos novamente.\n"
	.string "Posso pedir uma batalha?$"

Route104_Text_CindyRematchDefeat:
	.string "Poxa…\n"
	.string "Eu fiz o melhor que eu pude…$"

Route104_Text_CindyPostRematch:
	.string "“Olá” é só o início do “adeus.”\n"
	.string "Eu espero te ver novamente.$"

Route104_Text_DarianIntro:
	.string "Oba! Eu pesquei um Pokémon!\p"
	.string "Ele tem uma qualidade mágica!\n"
	.string "Ele parece näo fazer nada, mas faz!$"

Route104_Text_DarianDefeat:
	.string "Oh, Deus…$"

Route104_Text_DarianPostBattle:
	.string "Será que Magikarp pode viver fora\n"
	.string "d'água? Será possível$"

Route105_Text_FosterIntro:
	.string "Dizem que supostamente há\n"
	.string "uma rocha mística por aqui.\l"
	.string "Você sabe algo sobre isso?$"

Route105_Text_FosterDefeated:
	.string "Estava pensando tanto nessa rocha que\n"
	.string "eu deixei meus Pokémon perderem…$"

Route105_Text_FosterPostBattle:
	.string "Posso passar horas e horas observando\n"
	.string "uma rocha bonita sem me cansar.$"

Route105_Text_LuisIntro:
	.string "Ufa! Eu pensei que uma criança estava\n"
	.string "se afogando quando eu vi você.\p"
	.string "Você parece bem, entäo que tal\n"
	.string "uma batalha?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "Se você está se afogando, agite o braço\n"
	.string "para costa para pedir ajuda.$"

Route105_Text_DominikIntro:
	.string "Nadar entre as ondas do mar…\n"
	.string "É melhor que piscina!$"

Route105_Text_DominikDefeated:
	.string "Ah, entäo perdi…\n"
	.string "Que drepê…$"

Route105_Text_DominikPostBattle:
	.string "Por que o mar é azul?\p"
	.string "Eu li a explicaçäo no Museu em\n"
	.string "Slateport, mas eu näo lembro$"

Route105_Text_BeverlyIntro:
	.string "Meu corpo é bem mais ligeiro na água.\n"
	.string "É como se näo pesasse nada!$"

Route105_Text_BeverlyDefeated:
	.string "Tô flutuando…$"

Route105_Text_PostBattle:
	.string "O peso de seu corpo é nove vezes\n"
	.string "mais ligeiro na água.\p"
	.string "É normal quando nadar poder saltar…\n"
	.string "e mover-se muito bem!$"

Route105_Text_ImaniIntro:
	.string "O azul do céu…\n"
	.string "Esse vasto mar…\l"
	.string "Que tranquilidade…$"

Route105_Text_ImaniDefeated:
	.string "Perdi enquanto descansava!$"

Route105_Text_ImaniPostBattle:
	.string "Eu gosto quando fala que sou\n"
	.string "boa compahia, Hehehe.$"

Route105_Text_AndresIntro:
	.string "Tenho certeza que o mar\n"
	.string "tem incontáveis segredos.$"

Route105_Text_AndresDefeated:
	.string "Sim…\n"
	.string "Eu näo sou bom em combate…$"

Route105_Text_AndresPostBattle:
	.string "Tenho a certeza de que o mar\n"
	.string "guarda incontáveis segredos.\p"
	.string "Bem eu quero é descobrir todos!$"

Route105_Text_AndresRegister:
	.string "Huh? Eu näo sou forte e sim gordo\n"
	.string "quero me registrar em sua Pokénav?$"

Route105_Text_AndresRematchIntro:
	.string "Eu já te disse que sou fraco…\n"
	.string "Tem certeza que quer fazer isso?$"

Route105_Text_AndresRematchDefeated:
	.string "Sim…\n"
	.string "Näo achei que pudesse ganhar.$"

Route105_Text_AndresRematchPostBattle:
	.string "Eu posso ser fraco em lutar, mas\n"
	.string "minha qualidade em exploraçäo é\p"
	.string "incrível. Viajarei pelos mares de\n"
	.string "esse globo terrestre!$"

Route105_Text_JosueIntro:
	.string "Nadar me esgota uma barbaridade.\n"
	.string "Eu perdi o costume.\p"
	.string "Necessito de um combate, para variar!$"

Route105_Text_JosueDefeated:
	.string "Perdi, só porque estamos no mar.$"

Route105_Text_JosuePostBattle:
	.string "A verdade é que prefiro lutar\n"
	.string "no ar do que lutar no mar.$"

Route106_Text_ElliotIntro:
	.string "Qual você prefere, a pescaria no mar\n"
	.string "ou em córrego?$"

Route106_Text_ElliotDefeated:
	.string "Como na pesca de alto mar, eu perdi\n"
	.string "tudo… hehe!$"

Route106_Text_ElliotPostBattle:
	.string "Pescar e ótimo tanto no mar como\n"
	.string "em um córrego pequeno.\l"
	.string "Você concorda comigo, certo?$"

Route106_Text_ElliotRegister:
	.string "Pesca é bom, mas eu quero lutar.\n"
	.string "Se quiser, podemos nos encontar\n"
	.string "de novo.$"

Route106_Text_ElliotRematchIntro:
	.string "Peguei vários Pokémon peixes. Vou te\n"
	.string "mostrar uma batalha impressionante!$"

Route106_Text_ElliotRematchDefeated:
	.string "Em especial, perdi de novo!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Ganhar ou perder, Pokémon é o máximo!\n"
	.string "Você concorda comigo, né?$"

Route106_Text_NedIntro:
	.string "O que as pessoas fazem, se precisarem\n"
	.string "ir ao banheiro?\p"
	.string "E se o gancho da vara prender lá!\n"
	.string "Eu faço o que? Por isso eu näo vou…$"

Route106_Text_NedDefeated:
	.string "Perdi porque estou apertado.\n"
	.string "Vou logo ao banheiro…$"

Route106_Text_NedPostBattle:
	.string "Oh, näo! Eu acho que eu näo consegui\n"
	.string "segurar mais$"

Route106_Text_DouglasIntro:
	.string "Hahaha! Correndo sou uma tartaruga,\n"
	.string "mas na água eu sou um peixe!$"

Route106_Text_DouglasDefeated:
	.string "Eu desisto!$"

Route106_Text_DouglasPostBattle:
	.string "Näo perderia se fosse nataçäo…$"

Route106_Text_KylaIntro:
	.string "No mar sou a melhor. Eu näo vou ter\n"
	.string "pena, só porque você é uma criança!$"

Route106_Text_KylaDefeated:
	.string "Hehehe… Você näo me levou a sério,\n"
	.string "näo é?$"

Route106_Text_KylaPostBattle:
	.string "Nadar entre as ondas do mar…\n"
	.string "Eu amo isso! Por que näo experimenta?$"

Route107_Text_DarrinIntro:
	.string "Auaaaa…\p"
	.string "Eu devo ter dormido enquanto me\n"
	.string "fazia de morto entre as ondas.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, perdi…\n"
	.string "Que nada, vou dormir de novo…$"

Route107_Text_DarrinPostBattle:
	.string "Flutuar entre as ondas do mar\n"
	.string "é como dormir em uma cama\l"
	.string "macia e bem confortável.$"

Route107_Text_TonyIntro:
	.string "O mar é como meu quintal.\n"
	.string "Vamos batalhar!$"

Route107_Text_TonyDefeated:
	.string "Eu perdi em casa…\n"
	.string "Näo posso acreditar!$"

Route107_Text_TonyPostBattle:
	.string "Nado no mar com muita paixäo e garra.\n"
	.string "Nunca me canso…\p"
	.string "De fato, vou nadar um pouco mais.$"

Route107_Text_TonyRegister:
	.string "Seu estilo me deixou chocado!\n"
	.string "Espero que näo esqueça de mim…$"

Route107_Text_TonyRematchIntro:
	.string "Nadar neste enorme e imenso mar…\n"
	.string "… Isso tornará meu Pokémon mais forte.$"

Route107_Text_TonyRematchDefeated:
	.string "Que chocante!\p"
	.string "Meu Pokémon ficou mais forte, mas\n"
	.string "eu como treinador continuo fraco!$"

Route107_Text_TonyRematchPostBattle:
	.string "O que você aprende na batalha faz\n"
	.string "de você um treinador mais forte.\l"
	.string "As ondas me ensinaram isso.$"

Route107_Text_DeniseIntro:
	.string "Você conhece uma cidade chamada\n"
	.string "Dewford?$"

Route107_Text_DeniseDefeated:
	.string "Odeio isso!$"

Route107_Text_DenisePostBattle:
	.string "Há um dito popular que está na\n"
	.string "moda no Clube de Dewford.$"

Route107_Text_BethIntro:
	.string "Procurando por uma batalha?\n"
	.string "Entäo encontrou uma. Vamos!$"

Route107_Text_BethDefeated:
	.string "Eu näo estava a sua altura$"

Route107_Text_BethPostBattle:
	.string "Aposto o que seja que você vai continuar\n"
	.string "melhorando. E eu também!$"

Route107_Text_LisaIntro:
	.string "Lisa: Meu irmäo e eu te desafiamos\n"
	.string "para lutar!$"

Route107_Text_LisaDefeated:
	.string "Lisa: Que impressionante.\n"
	.string "É muito mais do que forte.$"

Route107_Text_LisaPostBattle:
	.string "Lisa: Você gosta de vim a praia\n"
	.string "com seus amigos para descansar?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "Lisa: Se deseja batalhar conosco,\n"
	.string "traga mais Pokémon.$"

Route107_Text_RayIntro:
	.string "Ray: Minha irmä e eu sempre lutamos\n"
	.string "com Pokémon.\p"
	.string "Eu sempre perco, mas agora é 2 contra 2!$"

Route107_Text_RayDefeated:
	.string "Ray: Poxa, seu nível é mais alto\n"
	.string "que o nosso!$"

Route107_Text_RayPostBattle:
	.string "Ray: Ganhei este Pokémon da\n"
	.string "minha irmä. Eu mesmo treinei e\l"
	.string "agora somos parceiros!$"

Route107_Text_RayNotEnoughPokemon:
	.string "Ray: Se quer batalhar conosco,\n"
	.string "deverá trazer mais Pokémon!$"

Route107_Text_CamronIntro:
	.string "Eu estou no meio de um triatlo,\n"
	.string "mas ainda eu tenho força!$"

Route107_Text_CamronDefeated:
	.string "Fiquei sem força…$"

Route107_Text_CamronPostBattle:
	.string "Ainda tenho que completar todas\n"
	.string "as provas que falta.\p"
	.string "Será que consigo treminar?$"

Route108_Text_JeromeIntro:
	.string "Hehehe… Meu sonho é nadar\n"
	.string "pelos sete mares!$"

Route108_Text_JeromeDefeated:
	.string "Assim eu näo chego nem no rio\n"
	.string "perto da esquina…$"

Route108_Text_JeromePostBattle:
	.string "O melhor de nadar é que pode brincar\n"
	.string "com os Pokémon marinhos.$"

Route108_Text_MatthewIntro:
	.string "Olá, jovem! Você também está indo\n"
	.string "para o navio abandonado?$"

Route108_Text_MatthewDefeated:
	.string "Eu afundei!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle:
	.string "Tem gente doida que entra\n"
	.string "no navio abandonado.$"

Route108_Text_TaraIntro:
	.string "Näo há nada mais cômodo que\n"
	.string "um bikini para ir para praia…$"

Route108_Text_TaraDefeated:
	.string "Oh, näo!$"

Route108_Text_TaraPostBattle:
	.string "Bem, talvez seja mais cômodo\n"
	.string "eu tomar sol, pois näo sou\p"
	.string "boa para batalhar…$"

Route108_Text_MissyIntro:
	.string "Eu amo o mar…\n"
	.string "Quando nado, esqueço meus problemas!$"

Route108_Text_MissyDefeated:
	.string "Perder batalhas me estressa,\n"
	.string "eu vou é nadar!$"

Route108_Text_MissyPostBattle:
	.string "Combate o estress nadando.\n"
	.string "Näo há rémedio melhor!$"

Route108_Text_CoryIntro:
	.string "Eu amo Pokémon de tipo Water.\n"
	.string "E amo os outros também!$"

Route108_Text_CoryDefeated:
	.string "Aaaaah! Perdi!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryPostBattle:
	.string "Gritar sempre é bom.\n"
	.string "Libera adrenalina!$"

Route108_Text_CoryRegister:
	.string "Eu amo treinadores duröes.\n"
	.string "Registre-me na sua Pokénav!$"

Route108_Text_CoryRematchIntro:
	.string "Ganha ou perde, Eu amo lutar no mar!$"

Route108_Text_CoryRematchDefeated:
	.string "Aaaaah! Perdi novamente!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "Se estiver diante de um desafio,\n"
	.string "tente gritar no mar!$"

Route108_Text_CarolinaIntro:
	.string "Estou orgulhosa dos meus Pokémon.\n"
	.string "Verá o que é lutar com rapidez!$"

Route108_Text_CarolinaDefeated:
	.string "Isso näo foi nada legal.$"

Route108_Text_CarolinaPostBattle:
	.string "Se você gosta de nadadores, igual a\n"
	.string "mim, o melhor e estar perto do mar…$"

Route109_Text_DavidIntro:
	.string "Hahahaha! Olhe só meu abdominal.\n"
	.string "E tudo é graças a nataçäo!$"

Route109_Text_DavidDefeated:
	.string "Ai, ai!\n"
	.string "Eu falhei!$"

Route109_Text_DavidPostBattle:
	.string "Hahaha!\p"
	.string "Meus abdominais de nada serve\n"
	.string "para os combates Pokémon!$"

Route109_Text_AliceIntro:
	.string "Humm…\n"
	.string "Você está bem protegido contra o sol?$"

Route109_Text_AliceDefeated:
	.string "Ai, ai, ai, ai!$"

Route109_Text_AlicePostBattle:
	.string "Bochechas säo mais fáceis de queimar!$"

Route109_Text_HueyIntro:
	.string "Eu já âncorei nos portos ao redor\n"
	.string "do mundo, mas Slateport é o melhor.$"

Route109_Text_HueyDefeated:
	.string "Você é o melhor!$"

Route109_Text_HueyPostBattle:
	.string "Um dia eu serei\n"
	.string "O melhor treinador!$"

Route109_Text_EdmondIntro:
	.string "Você ai…\n"
	.string "Batalhe? Comigo?$"

Route109_Text_EdmondDefeated:
	.string "Meu… Estômago dói…\n"
	.string "Ooooohhhhh…$"

Route109_Text_EdmondPostBattle:
	.string "Eu tenho o estômago bom.\n"
	.string "Mas fiquei enjoado… Oooh…\p"
	.string "Eu sou um marinheiro, mas…$"

Route109_Text_RickyIntro:
	.string "Estou com sede… Eu queria uma Soda Pop\n"
	.string "lá da casa de praia…$"

Route109_Text_RickyDefeated:
	.string "Perdi…$"

Route109_Text_RickyPostBattle:
	.string "Estou ficando faminto… Humm…\n"
	.string "Queria comer uma rosquinha gigante…$"

Route109_Text_RickyRegister:
	.string "Será que você quer lutar comigo\n"
	.string "quando eu näo tiver com sede?$"

Route109_Text_RickyRematchIntro:
	.string "Que fome… Mas ainda tenho\n"
	.string "energia para um combate.$"

Route109_Text_RickyRematchDefeated:
	.string "Perdi…\n"
	.string "Isso por que tenho fome…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quando faz um picnic na praia,\n"
	.string "tudo parece ter um sabor melhor$"

Route109_Text_LolaIntro:
	.string "Esse guarda-sol parece muito\n"
	.string "com uma flor gigante?$"

Route109_Text_LolaDefeated:
	.string "Aaaah!$"

Route109_Text_LolaPostBattle:
	.string "Se você olhar para a praia lá do céu,\n"
	.string "parece um jardim de flores grandes.$"

Route109_Text_LolaRegister:
	.string "Eu?\n"
	.string "Eu quero ser sua amiga.$"

Route109_Text_LolaRematchIntro:
	.string "No penso a voltar a perder!\n"
	.string "Por isso tenho minha bóia!$"

Route109_Text_LolaRematchDefeated:
	.string "Aaaah!$"

Route109_Text_LolaRematchPostBattle:
	.string "Graças a minha bóia, tanto eu como\n"
	.string "meus Pokémon estamos melhores!$"

Route109_Text_AustinaIntro:
	.string "Eu näo sei nadar sem minha bóia,\n"
	.string "mas com meu Pokémon eu ganho!$"

Route109_Text_AustinaDefeated:
	.string "Ah! Será que perdi por culpa\n"
	.string "desta bóia?$"

Route109_Text_AustinaPostBattle:
	.string "Minha bóia está super na moda!\n"
	.string "E eu näo tenho muito estilo.$"

Route109_Text_GwenIntro:
	.string "Olá, treinador.\n"
	.string "Você vai batalhar comigo?$"

Route109_Text_GwenDefeated:
	.string "Que forte você é$"

Route109_Text_GwenPostBattle:
	.string "Oh! Como faz para ser täo forte?$"

Route109_Text_CarterIntro:
	.string "Hahahaha! Me fale bobagem\n"
	.string "e vou te dar uma boa liçäo.$"

Route109_Text_CarterDefeated:
	.string "Eu que aprendi a liçäo…$"

Route109_Text_CarterPostBattle:
	.string "Pensei que você era um grande\n"
	.string "problema. Näo, você é bem legal!$"

Route109_Text_PaulIntro:
	.string "Paul: Oh, nosso clima acabou\p"
	.string "Ainda vem você para perturbar\n"
	.string "nosso tempo precioso juntos.$"

Route109_Text_PaulDefeated:
	.string "Paul: Bem, eu desisto.$"

Route109_Text_PaulPostBattle:
	.string "Paul: Bem, näo conte a ninguém que\n"
	.string "estamos aqui.\l"
	.string "Este é o nosso mundo privado à dois!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "Paul: Estamos totalmente apaixonados\n"
	.string "um pelo o outro.\n"
	.string "Por isso batalhamos juntos.$"

Route109_Text_MelIntro:
	.string "Mel: Estamos totalmente apaixonados.\n"
	.string "Nosso romance ferve tudo em Hoenn!$"

Route109_Text_MelDefeated:
	.string "Mel: Perdemos e a culpa é minha.\n"
	.string "Que chato isso…$"

Route109_Text_MelPostBattle:
	.string "Mel: Paul, na próxima vez terá\n"
	.string "que se esforçar mais$"

Route109_Text_MelNotEnoughPokemon:
	.string "Mel: Estamos totalmente apaixonados\n"
	.string "um pelo o outro.\n"
	.string "Por isso batalhamos juntos.$"

Route109_Text_ChandlerIntro:
	.string "Opa! Veja só?\n"
	.string "A minha bóia amarela!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "Perdi feio!$"

Route109_Text_ChandlerPostBattle:
	.string "Depois te empresto minha bóia\n"
	.string "amarela, ok…$"

Route109_Text_HaileyIntro:
	.string "Eu näo sei nadar.\n"
	.string "Mas eu finjo bem isso!$"

Route109_Text_HaileyDefeated:
	.string "Eu pensei que…\n"
	.string "Poderia ganhar mas perdi…$"

Route109_Text_HaileyPostBattle:
	.string "Eu näo sei nadar ainda…\n"
	.string "Mas meus Pokémon sabem mais do que eu.$"

Route109_Text_ElijahIntro:
	.string "Para um cara machista igual a mim,\n"
	.string "este tipo de Pokémon é perfeito!$"

Route109_Text_ElijahDefeated:
	.string "Sou legal até na derrota, né?$"

Route109_Text_ElijahPostBattle:
	.string "Os caras machista igual a mim\n"
	.string "tem uma noiva em cada porto!\p"
	.string "Acho que irei até Slateport.$"

Route110_Text_JacobIntro:
	.string "Uau! Cuidado! Eu acho que você\n"
	.string "näo pegou o jeito ainda.$"

Route110_Text_JacobDefeated:
	.string "Aaah!\n"
	.string "Estou sem freios!$"

Route110_Text_JacobPostBattle:
	.string "Pneus furados e problemas de freio\n"
	.string "podem causar ferimentos graves.\l"
	.string "Inspecione sua bicicleta!$"

Route110_Text_AnthonyIntro:
	.string "Ei, você!\n"
	.string "Você consegue me alcançar?$"

Route110_Text_AnthonyDefeated:
	.string "Sou o último!$"

Route110_Text_AnthonyPostBattle:
	.string "Näo basta só velocidade para ganhar\n"
	.string "batalhas Pokémon, esta óbvio…$"

Route110_Text_BenjaminIntro:
	.string "Näo se desespere se vai muito rápido!$"

Route110_Text_BenjaminDefeated:
	.string "Näo sei por que tenho medo\n"
	.string "nas batalhas…$"

Route110_Text_BenjaminPostBattle:
	.string "Näo precisa ficar em pânico ou estresse.\n"
	.string "Acalme-se. Há tempo de sobra.$"

Route110_Text_BenjaminRegister:
	.string "Eu vou manter meu o ritmo sem forçar.\n"
	.string "Dê-me uma revanche depois, tudo bem.$"

Route110_Text_BenjaminRematchIntro:
	.string "Você näo está indo rápido demais?\n"
	.string "Acalme-se e vamos batalhar.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Näo entrei em pânico, mas perdi…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Näo precisa ficar em pânico ou estresse.\n"
	.string "Acalme-se. Há tempo de sobra.$"

Route110_Text_AbigailIntro:
	.string "Triatlo é uma prova difícil ao extremo.\p"
	.string "Você tem que competir em 3 evento,\n"
	.string "em nataçäo, ciclismo e corrida.$"

Route110_Text_AbigailDefeated:
	.string "Batalhas Pokémon näo é fácil!$"

Route110_Text_AbigailPostBattle:
	.string "Estou exausta, eu preciso descansar.\n"
	.string "É importante näo sobrecarregar.$"

Route110_Text_AbigailRegister:
	.string "Poxa… agora eu te admiro!\n"
	.string "Vamos ter uma revanche depois.$"

Route110_Text_AbigailRematchIntro:
	.string "Vamos uma batalha enquanto\n"
	.string "andamos de bicicleta.$"

Route110_Text_AbigailRematchDefeated:
	.string "Uau…\n"
	.string "Como pode ser täo forte?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Você queria fazer um recorde?\p"
	.string "Me desculpe se eu segurei-te!$"

Route110_Text_JasmineIntro:
	.string "Ando tanto de bicicleta, que\n"
	.string "minhas coxas säo como pedras!$"

Route110_Text_JasmineDefeated:
	.string "Acho que me deu uma cäibras…$"

Route110_Text_JasminePostBattle:
	.string "Oh! Possui algumas Insígnias?\n"
	.string "Por isso você é täo forte!$"

Route110_Text_EdwardIntro:
	.string "Eu vou advinhar as suas intençöes.\n"
	.string "Näo posso perder!$"

Route110_Text_EdwardDefeated:
	.string "Eu näo advinhei o meu fracasso, snif!$"

Route110_Text_EdwardPostBattle:
	.string "Eu vejo o seu futuro…\p"
	.string "Hmm…\n"
	.string "Será brilhante…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "Admire minhas habilidades.$"

Route110_Text_JaclynDefeated:
	.string "Perdi maravilhosamente!$"

Route110_Text_JaclynPostBattle:
	.string "Você só conseguiu ganhar por\n"
	.string "causa da sorte! Sim, pura sorte!\l"
	.string "Näo pense que ganhará o tempo todo!$"

Route110_Text_EdwinIntro:
	.string "Posso ver o seu Pokémon?\n"
	.string "Só um vez, por favor?$"

Route110_Text_EdwinDefeated:
	.string "Eu queria completar \n"
	.string "minha coleçäo…$"

Route110_Text_EdwinPostBattle:
	.string "Quando eu vejo um Pokémon que eu näo\n"
	.string "conheço, a minha satisfaçäo só aumenta!$"

Route110_Text_EdwinRegister:
	.string "Eu gosto de colecionar muitos\n"
	.string "contatos, também…$"

Route110_Text_EdwinRematchIntro:
	.string "Oi, Já pegou algum Pokémon novo?\p"
	.string "Eu posso ver seu Pokémon?\n"
	.string "Só uma espiada, por favor?$"

Route110_Text_EdwinRematchDefeated:
	.string "Seu Pokémon…\n"
	.string "Eu invejo.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, Quero ter todos Pokémon\n"
	.string "raros comigo!$"

Route110_Text_DaleIntro:
	.string "Ei! Näo chegue por trás\n"
	.string "de mim assim!?!$"

Route110_Text_DaleDefeated:
	.string "Eu…\n"
	.string "…perdi!$"

Route110_Text_DalePostBattle:
	.string "Pescaria requer concentraçäo. Tem\n"
	.string "que se concentrar bem para pescar.$"

Route110_Text_IsabelIntro:
	.string "Eu quero ir ao Contest Pokémon,\n"
	.string "só para mostrar meus Pokémon!$"

Route110_Text_IsabelDefeated:
	.string "Oh, céus, isso näo vale.$"

Route110_Text_IsabelPostBattle:
	.string "Ao em vez de lutar, talvez eu deveria\n"
	.string "mostrar meus Pokémon lá no Fä Clube.$"

Route110_Text_IsabelRegister:
	.string "Eu näo sei o que fazer para o meu\n"
	.string "Pokémon ficar conhecido.\p"
	.string "Eu vou ter você como meu público\n"
	.string "cativo sempre que possível.$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Eu ficaria feliz em mostrar\n"
	.string "meus Pokémon sempre para você!$"

Route110_Text_IsabelRematchDefeated:
	.string "Poxa, isso näo se faz.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Eu näo acho que eu possa parar\n"
	.string "de mostrar os meus Pokémon.\p"
	.string "Mas eu gosto de batalha, também!$"

Route110_Text_TimmyIntro:
	.string "Eu encontrei Pokémon bem legais\n"
	.string "nessa grama aqui.$"

Route110_Text_TimmyDefeated:
	.string "Ser legal näo é tudo na vida…$"

Route110_Text_TimmyPostBattle:
	.string "É difícil lutar contra alguns\n"
	.string "tipos de Pokémon!$"

Route110_Text_AlyssaIntro:
	.string "Eu cai na ciclovia…\p"
	.string "Eu vou acabar com minha vergonha\n"
	.string "lutando com você agora.$"

Route110_Text_AlyssaDefeated:
	.string "Oops!\n"
	.string "Acabei perdendo!$"

Route110_Text_AlyssaPostBattle:
	.string "Cair… Perder…\n"
	.string "Isto é täo humilhante para mim!$"

Route110_Text_JosephIntro:
	.string "Ok! Seja rápido! Se você näo puder \n"
	.string "correr, entäo, eu vou te pegar!$"

Route110_Text_JosephDefeated:
	.string "Você näo entrou no ritmo certo…$"

Route110_Text_JosephPostBattle:
	.string "Isso näo vai me derrubar…\n"
	.string "Perder me fez um homem ainda melhor.!$"

Route110_Text_KalebIntro:
	.string "Que bonito ver um Pokémon ajudar…\n"
	.string "Você näo vai ver nada mais adorável.$"

Route110_Text_KalebDefeated:
	.string "Você näo tem compaixäo ou pena?$"

Route110_Text_KalebPostBattle:
	.string "Maravilha! Você fez muito bem\n"
	.string "a sua parte, muito legal.$"

Route111_Text_DrewIntro:
	.string "Ei, Ei! Aqueles Go-Googles serviu?\n"
	.string "Eu acho que eles parecem melhor em mim.\p"
	.string "Entäo…! Vamos decidir isso\n"
	.string "melhor na batalha!$"

Route111_Text_DrewDefeat:
	.string "Näo estou feliz porque o\n"
	.string "Go-Googles näo é meu.$"

Route111_Text_DrewPostBattle:
	.string "Ei, Ei! Aqueles Go-Googles serviu?\n"
	.string "Eu acho que eles parecem melhor em mim.\l"
	.string "Isso me faz feliz!$"

Route111_Text_HeidiIntro:
	.string "Faça um piquenique no deserto.\p"
	.string "Você sempre encontra um treinador.\n"
	.string "É bom lanchar e batalhar, também!$"

Route111_Text_HeidiDefeat:
	.string "Ah! Eu já perdi!$"

Route111_Text_HeidiPostBattle:
	.string "Quando você está lutando em uma\n"
	.string "tempestade, atente para o HP do\p"
	.string "Pokémon.Ele pode desmaiar\n"
	.string "se näo ficar de olho.$"

Route111_Text_BeauIntro:
	.string "Usando estes Go-Googles me faz sentir\n"
	.string "como um super-herói.\l"
	.string "Ninguém poderá me vencer!$"

Route111_Text_BeauDefeat:
	.string "Eu näo posso ganhar sempre…$"

Route111_Text_BeauPostBattle:
	.string "Eu vou ser um verdadeiro herói um dia.\n"
	.string "Vou trabalhar muito para fazer meus\l"
	.string "Pokémon mais fortes.$"

Route111_Text_BeckyIntro:
	.string "Já ouvi que fósseis podem ser\n"
	.string "encontrados no deserto. Mas onde?$"

Route111_Text_BeckyDefeat:
	.string "Eu vim e já fui…$"

Route111_Text_BeckyPostBattle:
	.string "Se podem encontrar fósseis no deserto,\n"
	.string "deveria ter sido um mar antes.$"

Route111_Text_DustyIntro:
	.string "Por 30 anos eu tenho procurado\n"
	.string "ruínas antigas.\l"
	.string "Estou sendo desafiado?$"

Route111_Text_DustyDefeat:
	.string "Embora eu tenha procurado ruínas,\n"
	.string "eu näo procurei por fortes Pokémon.$"

Route111_Text_DustyPostBattle:
	.string "Por 30 anos eu tenho procurado\n"
	.string "ruínas antigas.\p"
	.string "Näo, espera, foi por 40 anos?\n"
	.string "O que foi agora?$"

Route111_Text_DustyRegister:
	.string "Eu näo vou à procura\n"
	.string "de qualquer Pokémon. Ok…\p"
	.string "Eu quero revanche depois,\n"
	.string "registrei na Pokénav.$"

Route111_Text_DustyRematchIntro:
	.string "Durante 30 anos, tenho procurado\n"
	.string "ruínas antigas!\p"
	.string "Näo, espere, é 40 anos?\n"
	.string "De qualquer forma, quer batalhar?$"

Route111_Text_DustyRematchDefeat:
	.string "Eu näo encontrei ruínas, nem tenho\n"
	.string "nenhum Pokémon forte…$"

Route111_Text_DustyPostRematch:
	.string "Durante 30 anos, tenho procurado\n"
	.string "ruínas antigas!\p"
	.string "Näo, näo, espere, por 40 anos\n"
	.string "Eu procurei?\p"
	.string "Hmm… Poderia até ser 50 anos…\n"
	.string "Quanto tempo eu estive procurando?$"

Route111_Text_TravisIntro:
	.string "Eu tenho vitalidade!\n"
	.string "E o meu Pokémon, também!$"

Route111_Text_TravisDefeat:
	.string "Meu Pokémon perdeu…$"

Route111_Text_TravisPostBattle:
	.string "Quando um Treinador é cheio de vida,\n"
	.string "eu tenho que adimirá-lo.$"

Route111_Text_IreneIntro:
	.string "Eu näo sei onde você está indo,\n"
	.string "mas gostaria de batalhar?$"

Route111_Text_IreneDefeat:
	.string "Oh, você até que é bem forte!$"

Route111_Text_IrenePostBattle:
	.string "Eu estou pensando em ir ao topo do\n"
	.string "Mt. Chimney, mas a vista aqui é\l"
	.string "muito boa, também.$"

Route111_Text_DaisukeIntro:
	.string "Quando treino, eu desafio todos\n"
	.string "que encontro!$"

Route111_Text_DaisukeDefeat:
	.string "Ahh! Eu desisto!$"

Route111_Text_DaisukePostBattle:
	.string "Tudo que posso fazer é treinar até.\n"
	.string "Eu poder derrotar treinadores\l"
	.string "fortes como você.$"

Route111_Text_WiltonIntro:
	.string "Mostre-me toda a força que tem\n"
	.string "o seu Pokémon.$"

Route111_Text_WiltonDefeat:
	.string "Nossa! Você melhorou\n"
	.string "consideravelmente.$"

Route111_Text_WiltonPostBattle:
	.string "Os Pokémon e treinadores\n"
	.string "aprende muito nas batalhas.\p"
	.string "O importante é nunca desistir\n"
	.string "mesmo se você perder.$"

Route111_Text_WiltonRegister:
	.string "Há muito a ser aprendido com\n"
	.string "o seu estilo de treinamento.\p"
	.string "Solicitarei uma revanche\n"
	.string "se quiser.$"

Route111_Text_WiltonRematchIntro:
	.string "Estou treinando aqui para elevar\n"
	.string "para o próximo nível.\l"
	.string "Fica e treine com a gente!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, você está bem!$"

Route111_Text_WiltonPostRematch:
	.string "Já que você é täo forte, por que\n"
	.string "näo vai para a Liga Pokémon.$"

Route111_Text_BrookeIntro:
	.string "Ei, você?\n"
	.string "O seu Pokémon parece muito bem.\l"
	.string "Mas… Eu só acredito na batalha.$"

Route111_Text_BrookeDefeat:
	.string "Oh, Deus que pena perdi…\n"
	.string "Como eles säo fortes!$"

Route111_Text_BrookePostBattle:
	.string "Eu pensei que meu Pokémon estava\n"
	.string "evoluíndo bem, mas, oh, näo,\l"
	.string "ainda há muito a ser feito.$"

Route111_Text_BrookeRegister:
	.string "Eu quero ser amiga do treinador,\n"
	.string "mais forte que eu já vi.$"

Route111_Text_BrookeRematchIntro:
	.string "Você pode fazer Pokémon mais forte\n"
	.string "ou mais fraco dependendo dos golpes\l"
	.string "que ensina.\p"
	.string "Que tipos de golpes seu\n"
	.string "Pokémon sabe?$"

Route111_Text_BrookeRematchDefeat:
	.string "Uau! Você ensinou bons golpes!$"

Route111_Text_BrookePostRematch:
	.string "Talvez eu deveria ter parado meu\n"
	.string "Pokémon de evoluir até ele\l"
	.string "aprender golpes melhores…$"

Route111_Text_CeliaIntro:
	.string "Eu näo deveria vir para esse lugar\n"
	.string "fazer um piquenique.$"

Route111_Text_CeliaDefeat:
	.string "Caramba!\n"
	.string "Eu näo deveria ter vindo!$"

Route111_Text_CeliaPostBattle:
	.string "Em uma tempestade como esta\n"
	.string "Eu näo acho lugares para um piquenique\l"
	.string "mesmo com Go-Googles…$"

Route111_Text_BryanIntro:
	.string "Quäo forte você é?\n"
	.string "Mostre o seu segredo!$"

Route111_Text_BryanDefeat:
	.string "Nossa! A sua força!\n"
	.string "Ela é cheia de mistério!$"

Route111_Text_BryanPostBattle:
	.string "Neste deserto há mistérios\n"
	.string "em sua areia movediças!$"

Route111_Text_BrandenIntro:
	.string "Te dou um pouco do meu sanduíche\n"
	.string "se você perder.$"

Route111_Text_BrandenDefeat:
	.string "Droga! Eu pensei que um sanduíche\n"
	.string "bastava de suborno…$"

Route111_Text_BrandenPostBattle:
	.string "Meu Sandshrew ama comer\n"
	.string "meus sanduíches.$"

Route111_Text_TyronIntro:
	.string "Veja! Este é o meu Pokémon favorito.$"

Route111_Text_TyronDefeat:
	.string "Espere! Você ainda näo viu\n"
	.string "os meus Pokémon!?$"

Route111_Text_TyronPostBattle:
	.string "Ao ter uma batalha, fico preocupado\n"
	.string "em mostrar meus Pokémon.\p"
	.string "Eu aposto que todos ficam assim\n"
	.string "quando eles batalham, näo é?$"

Route111_Text_CelinaIntro:
	.string "Mostre-me como pôr um pouco\n"
	.string "de emoçäo em minha vida.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Meu…\n"
	.string "Isso foi emoçäo demais.$"

Route111_Text_CelinaPostBattle:
	.string "Meu coraçäo palpita!\n"
	.string "Você é um Treinador de futuro.$"

Route111_Text_HaydenIntro:
	.string "Quando você está täo faminto\n"
	.string "Näo sente pena de ninguém!$"

Route111_Text_HaydenDefeat:
	.string "Perdi…$"

Route111_Text_HaydenPostBattle:
	.string "Meu estômago está reclamando!\n"
	.string "Queria comer grelhados…$"

Route111_Text_BiancaIntro:
	.string "Você veio de Mauville?\n"
	.string "Entäo você deve estar cheio de energia.$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala!\n"
	.string "Isso foi o bastante!$"

Route111_Text_BiancaPostBattle:
	.string "Esta estrada aqui…\n"
	.string "É muito segura para viajar.$"

Route112_Text_BriceIntro:
	.string "Hahahaha!\n"
	.string "Que tal ter uma batalha?\l"
	.string "Você e eu?\l"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "Perdi!\n"
	.string "Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! Algo voou no meu nariz\n"
	.string "Hahahaha-hatchoo!$"

Route112_Text_TrentIntro:
	.string "Minhas pernas doem de tanto subir\n"
	.string "e descer as montanhas.\p"
	.string "Mas eu näo vou ceder facilmente,\n"
	.string "vamos lutar!$"

Route112_Text_TrentDefeat:
	.string "Ouch! Minhas pernas doem!$"

Route112_Text_TrentPostBattle:
	.string "Tente caminhar, eu quero dizer subir\n"
	.string "por estas trilhas da montanha com\l"
	.string "uma mochila muito pesada.\l"
	.string "Isso, certamente vai deixar o seu\p"
	.string "corpo todo dolorido.$"

Route112_Text_TrentRegister:
	.string "Ai, minhas pernas doem.\n"
	.string "Você pode pegar algumas ataduras\l"
	.string "na minha mochila?\p"
	.string "Näo, essa é a minha Pokénav!\n"
	.string "Oh, eu vou te registrar.$"

Route112_Text_TrentRematchIntro:
	.string "Fui manter a forma caminhando.\n"
	.string "Força, eu tenho de sobra!$"

Route112_Text_TrentRematchDefeat:
	.string "Fui superado na força?$"

Route112_Text_TrentRematchPostBattle:
	.string "Eu ouvir que há treinadores duröes\n"
	.string "lá no topo do Mt Chimney.\p"
	.string "Bem, eu pretendo chegar lá e\n"
	.string "chamá-los para um bom desafio!$"

Route112_Text_LarryIntro:
	.string "Eu näo vou chorar.\n"
	.string "Se eu perder.$"

Route112_Text_LarryDefeat:
	.string "Waaaah!$"

Route112_Text_LarryPostBattle:
	.string "Eu só choro de saudades!\n"
	.string "da minha mäe. Sniff…$"

Route112_Text_CarolIntro:
	.string "Quando você está em um piquenique,\n"
	.string "você tem que cantar.\l"
	.string "Vamos, cante comigo!$"

Route112_Text_CarolDefeat:
	.string "Oh, você é täo forte!$"

Route112_Text_CarolPostBattle:
	.string "Näo importa se você é bom ou\n"
	.string "ruim em cantar. Mas… Se você\p"
	.string "for o mais divertido,você ganha!$"

Route112_Text_BryantIntro:
	.string "Eu peguei Pokémon lá na Fiery Path!\n"
	.string "Dê uma olhada!$"

Route112_Text_BryantDefeat:
	.string "Perder assim é ruim demais!$"

Route112_Text_BryantPostBattle:
	.string "Gosto do jeito de sua batalha.\n"
	.string "Ela tem um certo charme.$"

Route112_Text_ShaylaIntro:
	.string "Oh, que adorável! Por favor, quero\n"
	.string "uma batalha romântica.\l"
	.string "Porque? Eu sou um pouco decente.$"

Route112_Text_ShaylaDefeat:
	.string "Oh, como você é forte.\n"
	.string "Você me deixou chocada!$"

Route112_Text_ShaylaPostBattle:
	.string "Você está ocupado agora?\n"
	.string "Nós poderiamos ter uma revanche agora.\l"
	.string "Mas está bem, se você näo pode…\l"
	.string "Deixa pra outra hora!$"

Route113_Text_JaylenIntro:
	.string "Você näo sabia, mas aqui\n"
	.string "é bem divertido.$"

Route113_Text_JaylenDefeat:
	.string "Vixi!\n"
	.string "Isso fede!$"

Route113_Text_JaylenPostBattle:
	.string "A cinza vulcânica bloqueia o sol,\n"
	.string "por isso näo fica muito quente.\p"
	.string "Isso é bom, eu näo suporto o calor!$"

Route113_Text_DillonIntro:
	.string "Erupçäo do vulcäo é uma prova\n"
	.string "de que a terra está viva.$"

Route113_Text_DillonDefeat:
	.string "Você é do tipo bem forte!$"

Route113_Text_DillonPostBattle:
	.string "Ouch! Owww! Eu näo posso ver!\n"
	.string "Eu tenho cinzas em meus olhos!\p"
	.string "Ai? Meus olhos?\p"
	.string "Ai, isso é muito ruim, mesmo…$"

Route113_Text_MadelineIntro:
	.string "Eu uso este guarda-sol para afastar\n"
	.string "esta nojenta cinza vulcânica do\l"
	.string "meu querido Numel.$"

Route113_Text_MadelineDefeat:
	.string "Huff, huff…\n"
	.string "Estou exausta…$"

Route113_Text_MadelinePostBattle:
	.string "Você é muito bom nisso.\n"
	.string "Eu estou impressionada!$"

Route113_Text_MadelineRegister:
	.string "Aqui, fique sob meu guarda-sol.\n"
	.string "Vou registar você na Pokénav.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, olá. Você de novo?\n"
	.string "Hum, que tal uma batalha?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, que incrível!$"

Route113_Text_MadelinePostRematch:
	.string "Você ficou muito bom nisso.\n"
	.string "Devo dizer que estou impressionado!$"

Route113_Text_LaoIntro:
	.string "A partir das cinzas eu pulo! Hiyah!\n"
	.string "Eu te desafio!$"

Route113_Text_LaoDefeat:
	.string "Com honra aceito perder!$"

Route113_Text_LaoPostBattle:
	.string "Eu vou refinar a arte da dissimulaçäo.\n"
	.string "Eu te digo adeus.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Testemunhe a ancestral técnica\n"
	.string "ninja de registro na Pokénav!$"

Route113_Text_LaoRematchIntro:
	.string "A partir das cinzas eu pulo! Hiyah!\n"
	.string "Eu te desafio!$"

Route113_Text_LaoRematchDefeat:
	.string "Com honra admito perder!$"

Route113_Text_LaoPostRematch:
	.string "Esconder-se impecável era desilusäo\n"
	.string "agora chega de batalhas imaturas…\p"
	.string "Eu te digo adeus.$"

Route113_Text_LungIntro:
	.string "Obrigado por me encontrar!\n"
	.string "Mas temos que batalhar!$"

Route113_Text_LungDefeat:
	.string "Olha o meu golpe ninjutsu a…\n"
	.string "“Volcanic Ash Swirl Cloak”!\p"
	.string "…O que?\n"
	.string "E já acabou?$"

Route113_Text_LungPostBattle:
	.string "Você sabe o que é péssimo em esconder?\n"
	.string "É solitário, se ninguém vem.$"

Route113_Text_ToriIntro:
	.string "Tori:  Eu e ela, nós coletamos cinzas.\n"
	.string "E batalhamos juntas.$"

Route113_Text_ToriDefeat:
	.string "Tori: Que chato perdemos…\n"
	.string "Vou continuar a coletar mais cinzas.$"

Route113_Text_ToriPostBattle:
	.string "Tori: Quanta cinza temos?\n"
	.string "Será suficiente para uma White Flute.$"

Route113_Text_ToriNotEnoughMons:
	.string "Tori: Queremos combate 2-a-2.\n"
	.string "Assim, fica mais fácil ganhar!"

Route113_Text_TiaIntro:
	.string "Tia: Eu e ela, nós coletamos cinzas.\n"
	.string "E batalhamos juntas.$"

Route113_Text_TiaDefeat:
	.string "Tia: Nós perdemos… É chato,\n"
	.string "vou coletar mais um pouco de cinzas. $"

Route113_Text_TiaPostBattle:
	.string "Tia: Oba! Já temos as cinzas suficientes\n"
	.string "para uma White Flute!$"

Route113_Text_TiaNotEnoughMons:
	.string "Tia: Queremos combate 2-a-2.\n"
	.string "Se näo, näo vamos ganhar!$"

Route113_Text_CobyIntro:
	.string "Uauuu!\n"
	.string "Com asas eu poderia ir täo distante!$"

Route113_Text_CobyDefeat:
	.string "O… Que? $"

Route113_Text_CobyPostBattle:
	.string "Você ganhou com tanta facilidade\n"
	.string "estou sem palavras…$"

Route113_Text_SophieIntro:
	.string "O calor aqui me deixa sonolenta.\n"
	.string "BATALHE comigo para eu ficar acordada.$"

Route113_Text_SophieDefeat:
	.string "Isso é um sonho.\n"
	.string "Certamente é…$"

Route113_Text_SophiePostBattle:
	.string "Perder me irrita muito…\n"
	.string "Eu vou dormir aqui mesmo!\l"
	.string "Zzz! Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Será que existe maneira de\n"
	.string "recolher as cinzas vulcânicas?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "Agora estamos limpos.$"

Route113_Text_LawrencePostBattle:
	.string "Devo esconder sob as cinzas, também.$"

Route113_Text_WyattIntro:
	.string "Ei, V-você quer lutar comigo?\n"
	.string "Veja só… Os Pokémon que eu peguei.$"

Route113_Text_WyattDefeat:
	.string "V-você está feliz em ganhar?\n"
	.string "Ah… Mesmo sendo comigo?$"

Route113_Text_WyattPostBattle:
	.string "Ah, entäo agora eu sinto o gosto\n"
	.string "de uma derrota?\p"
	.string "Uma OVA!\n"
	.string "Você näo é o mais legal.$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "Você deveria gritar\n"
	.string "“yodelayhihoo” já que aqui\l"
	.string "näo tem echo!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "Quando eu era criança, eu achava que\n"
	.string "era alguém me copiando e gritando\l"
	.string "de volta, “Yodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "Se você näo consegue\n"
	.string "Você näo deveria subir as montanhas!$"

Route114_Text_LucasDefeat:
	.string "As montanhas säo implacáveis…$"

Route114_Text_LucasPostBattle:
	.string "No inverno, as montanhas fica mortal\n"
	.string "com nevascas e avalanches.$"

Route114_Text_ShaneIntro:
	.string "Acampar é divertido! Você pode pescar,\n"
	.string "assar marshmallows e contar histórias\p"
	.string "ASSUSTADORAS!\n"
	.string "Mas eu gosto é de batalhar!$"

Route114_Text_ShaneDefeat:
	.string "É muito forte!$"

Route114_Text_ShanePostBattle:
	.string "Eu acho isso ótimo!\n"
	.string "Poder ir acampar com os meus Pokémon.$"

Route114_Text_NancyIntro:
	.string "Tem que exercitar após uma refeiçäo.\n"
	.string "VAMOS BATALHAR!$"

Route114_Text_NancyDefeat:
	.string "Poxa!$"

Route114_Text_NancyPostBattle:
	.string "Só tinha refeiçäo saborosa.\n"
	.string "Estou SONOLENTA…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Quer lutar contra o meu Pokémon?$"

Route114_Text_SteveDefeat:
	.string "Meu Pokémon…$"

Route114_Text_StevePostBattle:
	.string "Um grande corpo todo irregular e duro,\n"
	.string "chifres enormes, e presas cruéis…\p"
	.string "Ufufufufu…\n"
	.string "Eu queria ter um Pokémon assim…$"

Route114_Text_SteveRegister:
	.string "Minha derrota foi bem humilhante!\n"
	.string "Quero te registrar e nunca esquecer!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Vamos, batalhar meu Pokémon…$"

Route114_Text_SteveRematchDefeat:
	.string "Sinto-me täo sortudo ao ver\n"
	.string "os seus Pokémon…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Quando eu vejo combates Pokémon,\n"
	.string "eu fico trêmulo e suado…$"

Route114_Text_BernieIntro:
	.string "Se você vai ACENDER uma fogueira,\n"
	.string "veja se você tem água à mäo.$"

Route114_Text_BernieDefeat:
	.string "Obrigado, apaguei meu fogo!$"

Route114_Text_BerniePostBattle:
	.string "Você deve ter muito cuidado com qualquer\n"
	.string "tipo de incêndio em uma floresta.\p"
	.string "Nunca subestime o poder do fogo.$"

Route114_Text_BernieRegister:
	.string "Você deixou-me em chamas.\n"
	.string "Vou registrar seu contato!$"

Route114_Text_BernieRematchIntro:
	.string "Você aprendeu a manter água à mäo\n"
	.string "para fogueiras?$"

Route114_Text_BernieRematchDefeat:
	.string "Eu fui molhado antes que eu\n"
	.string "pudesse me incendiar.$"

Route114_Text_BerniePostRematch:
	.string "Você deve ter cuidado com qualquer\n"
	.string "tipo de incêndio em uma floresta.\p"
	.string "Atençäo!\n"
	.string "Nunca subestime o poder do fogo.$"

Route114_Text_ClaudeIntro:
	.string "Se fosse PESCANDO, você näo teria\n"
	.string "chance contra mim.\l"
	.string "Entäo, mostre o seu Pokémon aí!$"

Route114_Text_ClaudeDefeat:
	.string "Se fosse na pesca, eu teria ganho…$"

Route114_Text_ClaudePostBattle:
	.string "Acho que vou tentar a minha sorte no\n"
	.string "poço grande na  Meteor Falls.\p"
	.string "Deve haver alguma coisa lá.\n"
	.string "Eu só sei disso.$"

Route114_Text_NolanIntro:
	.string "Eu gosto de pescar e de batalhas!\n"
	.string "Se alguém me desafia, eu estou lá,p"
	.string "até quando estou pescando.$"

Route114_Text_NolanDefeat:
	.string "Eu gosto de batalha, mas näo\n"
	.string "acho que eu sou bom nisso…$"

Route114_Text_NolanPostBattle:
	.string "Agora eu sei!\p"
	.string "Eu sempre achei que, eu näo posso\n"
	.string "ficar longe da pesca e dos Pokémon.$"

Route114_Text_TyraIntro:
	.string "Tyra: Muito bem. Eu já estou no clima…\n"
	.string "Vou te ensinar um pouco sobre Pokémon.$"

Route114_Text_TyraDefeat:
	.string "Tyra: Que estilo de luta incrível!$"

Route114_Text_TyraPostBattle:
	.string "Tyra: Eu ensinava para Ivy tudo\n"
	.string "sobre os Pokémon.$"

Route114_Text_TyraNotEnoughMons:
	.string "Tyra: Poxa…\n"
	.string "Se quer batalhar com a gente, só um \l"
	.string "Pokémon näo é suficiente!$"

Route114_Text_IvyIntro:
	.string "Ivy: Onde aprendeu sobre Pokémon?$"

Route114_Text_IvyDefeat:
	.string "Ivy: Que estilo de luta incrível!$"

Route114_Text_IvyPostBattle:
	.string "Ivy: Eu comecei a treinar Pokémon\n"
	.string "porque Tyra, minha tutora, ensinou-me!$"

Route114_Text_IvyNotEnoughMons:
	.string "Ivy: Você só tem um Pokémon?\n"
	.string "Eu acho que ele deve ser solitário.$"

Route114_Text_KaiIntro:
	.string "Consegui um dos grandes!\n"
	.string "Enorme! eu digo!$"

Route114_Text_KaiDefeat:
	.string "O que foi aquilo?\n"
	.string "Será que o meu perdeu?$"

Route114_Text_KaiPostBattle:
	.string "Okay!\n"
	.string "Ok! Eu vou pescar um maior ainda!$"

Route114_Text_CharlotteIntro:
	.string "Eu?!\n"
	.string "Sou só um rostinho bonito!$"

Route114_Text_CharlotteDefeat:
	.string "Isso näo foi nada bonito!$"

Route114_Text_CharlottePostBattle:
	.string "Eu näo quero um Pokémon\n"
	.string "que é apenas bonito.\p"
	.string "Eu adoro os bonitos e que têm força!$"

Route114_Text_AngelinaIntro:
	.string "Será que você já fez o seu\n"
	.string "Pokémon evoluir?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, veja só.\n"
	.string "Isso é bom saber.$"

Route114_Text_AngelinaPostBattle:
	.string "Algumas mudanças quando o Pokémon\n"
	.string "evoluem, é surpreendente!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "Você parece capaz…\l"
	.string "Deixe-me lhe fazer companhia!$"

Route115_Text_TimothyDefeat:
	.string "Você é mais forte do que\n"
	.string "Eu imaginava!$"

Route115_Text_TimothyPostBattle:
	.string "Näo existe tal coisa como nascer gênio.\n"
	.string "Tudo depende do esforço!\l"
	.string "É nisso que eu acredito…$"

Route115_Text_TimothyRegister:
	.string "Hmm… A perda completa tem sido\n"
	.string "uma memória distante.\p"
	.string "Se você permitir, eu desejo outra\n"
	.string "oportunidade para uma batalha.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Como sempre, sua agilidade fala\n"
	.string "por si. Vem, me fazer companhia!$"

Route115_Text_TimothyRematchDefeat:
	.string "Continua forte!$"

Route115_Text_TimothyPostRematch:
	.string "Só é preciso esforço!\p"
	.string "Perdi porque näo coloquei\n"
	.string "o esforço suficiente!$"

Route115_Text_KoichiIntro:
	.string "Você!\p"
	.string "My Machop!\p"
	.string "Quer batalhar!$"

Route115_Text_KoichiDefeat:
	.string "Ouch, ouch, ouch!$"

Route115_Text_KoichiPostBattle:
	.string "My Machop!\p"
	.string "Enquanto eles buscam o poder,\n"
	.string "eu vou crescer forte com eles.!$"

Route115_Text_NobIntro:
	.string "Minha melhor habilidade é quebrar\n"
	.string "tijolos com a testa!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"
	.string "Minha cabeça dói!$"

Route115_Text_NobPostBattle:
	.string "Eu vou ensinar karatê para meu\p"
	.string "Pokémon. Parece que vai ficar \n"
	.string "muito melhor do que eu.$"

Route115_Text_NobRegister:
	.string "Você é impressionante!\n"
	.string "Dê-me uma revanche depois, tudo bem?$"

Route115_Text_NobRematchIntro:
	.string "Após perder, treinamos duro para\n"
	.string "melhorar as habilidades.\l"
	.string "Vamos, dê-nos uma revanche!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "Perdemos de novo!$"

Route115_Text_NobPostRematch:
	.string "Meu Pokémon vai crescer forte!\n"
	.string "Vou redobrar meus treinos!$"

Route115_Text_CyndyIntro:
	.string "Esta praia é o meu local secreto!\n"
	.string "Näo venha intrometer-se!$"

Route115_Text_CyndyDefeat:
	.string "Eu já treinei bastante!$"

Route115_Text_CyndyPostBattle:
	.string "A areia é boa e serve para reduzir\n"
	.string "impactos e evitar lesöes.\l"
	.string "Este é o lugar perfeito para treinar.$"

Route115_Text_CyndyRegister:
	.string "Ok, você está livre para vir aqui.\n"
	.string " Eu quero lutar com você de novo.$"

Route115_Text_CyndyRematchIntro:
	.string "Ok, vamos começar essa batalha!$"

Route115_Text_CyndyRematchDefeat:
	.string "Posso lutar mas meu Pokémon…$"

Route115_Text_CyndyPostRematch:
	.string "Mesmo perdendo, eu ainda\n"
	.string "sinto algum prazer com isso.\l"
	.string "Deve ser por que eu amo Pokémon.$"

Route115_Text_HectorIntro:
	.string "Eu tenho um Pokémon raro!\n"
	.string "Quer que eu te mostre?$"

Route115_Text_HectorDefeat:
	.string "Você…\n"
	.string "Você quer meu Pokémon, näo é?$"

Route115_Text_HectorPostBattle:
	.string "Eu tenho esse Pokémon raro.\n"
	.string "É o bastante… Estou satisfeito.$"

Route115_Text_KyraIntro:
	.string "Eu vou lutar e ainda correr!\n"
	.string "Tente manter-se comigo!$"

Route115_Text_KyraDefeat:
	.string "Gasp, gasp…$"

Route115_Text_KyraPostBattle:
	.string "Eu cometi um erro de tentar \n"
	.string "batalhar e correr.\p"
	.string "Eu deveria dá um tempo para se acalmar…$"

Route115_Text_JaidenIntro:
	.string "Tome isso!\n"
	.string "Ultra ataque ninja Pokémon!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "A estratégia falhou!$"

Route115_Text_JaidenPostBattle:
	.string "Mas meus Pokémon foram ultra,\n"
	.string "näo foram?$"

Route115_Text_HeleneIntro:
	.string "Meu Pokémontem nível faixa-preta\n"
	.string "de força!$"

Route115_Text_HeleneDefeat:
	.string "Isto é muito humilhante!$"

Route115_Text_HelenePostBattle:
	.string "Eu nunca encontrei alguém melhor\n"
	.string "do que eu…\p"
	.string "Eu entendo agora!\n"
	.string "Você é o Líder do Ginásio, näo é?$"

Route115_Text_AlixIntro:
	.string "Ah… Te encontrei!\n"
	.string "Näo há como fugir agora!$"

Route115_Text_AlixDefeat:
	.string "Gah!\n"
	.string "Que ruim!$"

Route115_Text_AlixPostBattle:
	.string "Oh! Eu vou teletransportar para casa.$"

Route115_Text_MarleneIntro:
	.string "Você acabou minha meditaçäo…\n"
	.string "Você vai ser punido por isso.$"

Route115_Text_MarleneDefeat:
	.string "Poxa! Você me desconcentrou!$"

Route115_Text_MarlenePostBattle:
	.string "Eu meditava com o meu Pokémon.\n"
	.string "Mas este lugar näo é muito tranquilo…$"

Route116_Text_ClarkIntro:
	.string "Naquele túnel näo passa ninguém.\n"
	.string "Venha lutar comigo agora, certo!$"

Route116_Text_ClarkDefeat:
	.string "Coff… Coff…\n"
	.string "Perder me fez cansar…$"

Route116_Text_ClarkPostBattle:
	.string "Parece difícil né? Mas para um andarilho,\n"
	.string "as montanhas säo estradas.$"

Route116_Text_JoeyIntro:
	.string "Venha, quero lutar!\n"
	.string "Prepare-se!$"

Route116_Text_JoeyDefeat:
	.string "Ai! Um arranhäo!\n"
	.string "Vou colocar um curativo.$"

Route116_Text_JoeyPostBattle:
	.string "Curativos säo sinais de resistência. \n"
	.string "Eu já tenho um!$"

Route116_Text_JoseIntro:
	.string "Tenho Pokémon insetos!\n"
	.string "Quero batalhar!$"

Route116_Text_JoseDefeat:
	.string "Eu perdi!\n"
	.string "Ah, quase ganhei.$"

Route116_Text_JosePostBattle:
	.string "Os Pokémon insetos evolui rápido.\n"
	.string "Eles ficam muito fortes!$"

Route116_Text_JaniceIntro:
	.string "Olha só como é adorável e forte\n"
	.string "esse meu Pokémon!$"

Route116_Text_JaniceDefeat:
	.string "Perdi… Você é bem forte!$"

Route116_Text_JanicePostBattle:
	.string "Os Pokémon que possuem beleza e\n"
	.string "poder,  que é o ideal, eu acho.$"

Route116_Text_JerryIntro:
	.string "Aprendemos várias coisas úteis na \n"
	.string "escola de treinadores.\p"
	.string "Eu quero testar o que aprendi!$"

Route116_Text_JerryDefeat:
	.string "Eu estudei pouco…\n"
	.string "É por isso que eu perdi!$"

Route116_Text_JerryPostBattle:
	.string "Eu vou ter que repetir alguns cursos\n"
	.string "na escola de treinadores depois.\l"
	.string "Se näo, eu nunca serei como Roxanne.$"

Route116_Text_JerryRegister1:
	.string "Eu aprendi na escola de treinadores\n"
	.string "que a Pokénav pode registrar.\p"
	.string "Eu näo sei muito bem como é, mas…\n"
	.string "Vamos tentar registrar?$"

Route116_Text_JerryRegister2:
	.string "Eu aprendi na escola DE treinadores\n"
	.string "que a Pokénav pode registrar contatos.\p"
	.string "Eu näo sei o que significa isso mas,\n"
	.string "eu posso tentar?$"

Route116_Text_JerryRematchIntro:
	.string "Tenho estudando seriamente lá\n"
	.string "na escola. Eu näo vou perder,\l"
	.string "como eu fiz da última vez.$"

Route116_Text_JerryRematchDefeat:
	.string "Hunh?\n"
	.string "Eu estudei com afinco.$"

Route116_Text_JerryPostRematch:
	.string "Poxa, vou ter que refazer alguns\n"
	.string "cursos lá na escola.\l"
	.string "Se näo, Roxanne irá ficar muito brava.$"

Route116_Text_KarenIntro:
	.string " Perdi feio!\n"
	.string "Santo Arceus!$"

Route116_Text_KarenDefeat:
	.string "Estou em choque! Como perdi?$"

Route116_Text_KarenPostBattle:
	.string "Poxa! Assim eu nunca serei uma líder\n"
	.string "como Roxanne desta maneira!$"

Route116_Text_KarenRegister1:
	.string "Oh, Uau! Isso é uma Pokénav?\n"
	.string "Eu tenho uma. Por favor, registre-me!$"

Route116_Text_KarenRegister2:
	.string "Oh, Uau! Isso é uma Pokénav?\n"
	.string "Eu tenho uma. Por favor, registre-me!$"

Route116_Text_KarenRematchIntro:
	.string "Eu estudei muito desde que te vi.\n"
	.string "Venha ver as minhas conquistas!$"

Route116_Text_KarenRematchDefeat:
	.string "Tô chocada.\n"
	.string "Perdi de novo?$"

Route116_Text_KarenPostRematch:
	.string "Você derrotou Roxanne?\n"
	.string "Eu näo ganhei de você, ainda.$"

Route116_Text_SarahIntro:
	.string "Só para você saber\n"
	.string "Nunca fui superada por ninguém na vida.$"

Route116_Text_SarahDefeat:
	.string "Oh, santo Arceus!\n"
	.string "Foi uma experiência nova para mim.$"

Route116_Text_SarahPostBattle:
	.string "Minha vida de luxo dá-me tudo o que eu\n"
	.string "poderia desejar.\p"
	.string "Mas, quando se trata de Pokémon,\n"
	.string "minha riqueza näo faz sentido.$"

Route116_Text_DawsonIntro:
	.string "Quando você olhou para meu Pokémon\n"
	.string "eu pensei, se você näo fugir acho que\l"
	.string "podemos batalhar.$"

Route116_Text_DawsonDefeat:
	.string "Oh, baby, näo fique assim!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, näo, näo!\n"
	.string "Olha o pelô do meu Pokémon!\l"
	.string "Você arruinou meu penteado, também!\l"
	.string "Agora tenho que ir ao cabelereiro.$"

Route116_Text_DevanIntro:
	.string "Ei, eu te desafio?!?$"

Route116_Text_DevanDefeat:
	.string "Oh!\n"
	.string "Näo tem como competir!$"

Route116_Text_DevanPostBattle:
	.string "Eu deveria pegar Pokémon diferentes.\n"
	.string "É o que eu vou fazer agora!$"

Route116_Text_JohnsonIntro:
	.string "É um beco sem saída aqui.\n"
	.string "Oh, que tédio, vamos lutar?$"

Route116_Text_JohnsonDefeat:
	.string "Isso foi divertido, mas eu perdi.$"

Route116_Text_JohnsonPostBattle:
	.string "Fique aqui comigo e me faça companhia?$"

Route117_Text_IsaacIntro:
	.string "Eu quero batalhar bastante.\n"
	.string "Para elevar os meus Pokémon!$"

Route117_Text_IsaacDefeat:
	.string "Você criou bem o seu Pokémon…$"

Route117_Text_IsaacPostBattle:
	.string "Os Pokémon näo säo apenas poder.\p"
	.string "Cuidar deles faz você tornar-se uma\n"
	.string "pessoa melhor e um ótimo treinador.$"

Route117_Text_IsaacRegister:
	.string "Vou redobrar meus treinamentos.\n"
	.string "Poderia vir me visitar depois?$"

Route117_Text_IsaacRematchIntro:
	.string "Os Pokémon que eu tenho treinado\n"
	.string "estäo bem fortes, igual a antes.$"

Route117_Text_IsaacRematchDefeat:
	.string "Você sabe como criá-los muito bem.\n"
	.string "Pode até trabalhar no Day Care…$"

Route117_Text_IsaacPostRematch:
	.string "Seus Pokémon estäo crescendo bem!\n"
	.string "Deveria competir nos Contests.$"

Route117_Text_LydiaIntro:
	.string "Por favor, permita-me avaliar se você\n"
	.string "elevou bem os seus Pokémon.$"

Route117_Text_LydiaDefeat:
	.string "Sim, eles estäo muito bem.$"

Route117_Text_LydiaPostBattle:
	.string "Tente elevar todos os seus Pokémon!\n"
	.string "Mas näo deixe faltar atençäo.$"

Route117_Text_LydiaRegister:
	.string "Eu estou feliz porque eu conheci\n"
	.string "um treinador assim como você.$"

Route117_Text_LydiaRematchIntro:
	.string "Permita-me reavaliar se você treinou\n"
	.string "seus Pokémon corretamente.$"

Route117_Text_LydiaRematchDefeat:
	.string "Eles estäo muito admirável.$"

Route117_Text_LydiaPostRematch:
	.string "Pokémon gostam de diferentes tipos de\n"
	.string "{POKEBLOCK}s, dependendo da sua natureza.$"

Route117_Text_DylanIntro:
	.string "Eu estou no meio de um triatlo, mas,\n"
	.string "se você quiser, vamos batalhar!$"

Route117_Text_DylanDefeat:
	.string "Fiquei sem energia!$"

Route117_Text_DylanPostBattle:
	.string "Eu só estrago tudo…\p"
	.string "Eu poderia ganhar, mas…\n"
	.string "Essa batalha foi difícil!$"

Route117_Text_DylanRegister:
	.string "Pokémon tem que ser forte?\n"
	.string "Eu também queria ser, heheh!$"

Route117_Text_DylanRematchIntro:
	.string "Estou bem no meio de um triatlo,\n"
	.string "mas estou bem à frente de todos.\l"
	.string "Vamos ter uma batalha rápida!$"

Route117_Text_DylanRematchDefeat:
	.string "Fiquei sem energia novamente.$"

Route117_Text_DylanPostRematch:
	.string "Eu sou top em nataçäo e ciclismo,\n"
	.string "mas näo estou muito confiante\l"
	.string "com os Pokémon ainda.$"

Route117_Text_MariaIntro:
	.string "Eu faço o meu triaton com meus Pokémon,\n"
	.string "por isso tenho confiança e velocidade.$"

Route117_Text_MariaDefeat:
	.string "Preciso praticar muito mais…\n"
	.string "Eu acho…$"

Route117_Text_MariaPostBattle:
	.string "O treinamento só funciona se você\n"
	.string "mantê-lo regularmente.\p"
	.string "Ok! Eu vou continuar correndo!\n"
	.string "Heheheh!$"

Route117_Text_MariaRegister:
	.string "Você parece um treinador experiente.\n"
	.string "Se você quiser lutaremos depois!$"

Route117_Text_MariaRematchIntro:
	.string "Você está mantendo seu treinamento?\n"
	.string "Eu estou!\l"
	.string "Deixe-me mostrar a evidência!$"

Route117_Text_MariaRematchDefeat:
	.string "Eu preciso praticar muito mais,\n"
	.string "eu acho.$"

Route117_Text_MariaPostRematch:
	.string "Eu votarei a treinar amanhä.\n"
	.string "Vamos lutar novamente depois!$"

Route117_Text_DerekIntro:
	.string "Já fui um Caçador!\n"
	.string "E agora sou um Maníaco!\p"
	.string "Mas meu amor por Pokémon\n"
	.string "continua firme.$"

Route117_Text_DerekDefeat:
	.string "Meu jeito continua inalterado\n"
	.string "também…$"

Route117_Text_DerekPostBattle:
	.string "Tudo que fiz foi seguir o meu coraçäo,\n"
	.string "e agora eles me chamam de Maníaco…\p"
	.string "Eu sou um especialista,\n"
	.string "em Pokémon insetos!\l"
	.string "Será natural gostar de insetos assim?$"

Route117_Text_AnnaIntro:
	.string "Anna: Eu estou com minha parceira\n"
	.string "da escola. Eu tenho que ganhar.$"

Route117_Text_AnnaDefeat:
	.string "Anna: Eu estou com minha parceira.\n"
	.string "Mas näo consegui ganhar…$"

Route117_Text_AnnaPostBattle:
	.string "Anna: Seu Pokémon têm boas\n"
	.string "combinaçöes.\p"
	.string "Eu diria que você é um bom treinador!$"

Route117_Text_AnnaAndMegRegister:
	.string "Anna: Näo podemos perder assim!\n"
	.string "Você vai voltar, näo vai?$"

Route117_Text_AnnaNotEnoughMons:
	.string "Anna: Se quer lutar contra nós,\n"
	.string "traga 2 Pokémon com você.$"

Route117_Text_MegIntro:
	.string "Meg: Eu vou falar com minha super\n"
	.string "parceira para bater muito em você.$"

Route117_Text_MegDefeat:
	.string "Meg: Oh, näo!\n"
	.string "Sinto muito, Anna! Eu perdi…$"

Route117_Text_MegPostBattle:
	.string "Meg: Eu deixei Anna triste…\n"
	.string "Por isso ela näo venceu você.$"

Route117_Text_MegNotEnoughMons:
	.string "Meg: Você só tem um Pokémon?\n"
	.string "Entäo, nós näo podemos lutar com você.\p"
	.string "Queremos ter um combate 2-a-2.$"

Route117_Text_AnnaRematchIntro:
	.string "Anna: Näo posso continuar perdendo\n"
	.string "em frente a minha parceira?$"

Route117_Text_AnnaRematchDefeat:
	.string "Anna: Näo consegui entrar no ritmo.$"

Route117_Text_AnnaPostRematch:
	.string "Anna: Seus Pokémon têm boas\n"
	.string "combinaçöes.\p"
	.string "Eu diria que você é o segundo para nós!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "Anna: Se quer batalhar contra nós,\n"
	.string "entäo traga 2 Pokémon.$"

Route117_Text_MegRematchIntro:
	.string "Meg: Eu vou lutar com a minha\n"
	.string "parceira e ganhar dessa vez!$"

Route117_Text_MegRematchDefeat:
	.string "Meg: Täo forte!$"

Route117_Text_MegPostRematch:
	.string "Meg: Eu lutei junto com minha\n"
	.string "parceira, mas perdemos…\p"
	.string "Isso é täo desanimador…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "Meg: Você só tem 1 Pokémon?\n"
	.string "Näo podemos lutar com você, entäo.\p"
	.string "Queremos ter uma batalha 2-contra-2.$"

Route117_Text_MelinaIntro:
	.string "Näo é legal? Podemos batalhar e olhar\n"
	.string "as flores bonitas?$"

Route117_Text_MelinaDefeat:
	.string "Ah, isso é impressionante!$"

Route117_Text_MelinaPostBattle:
	.string "É uma sensaçäo maravilhosa correr\n"
	.string "enquanto olho as flores.$"

Route117_Text_BrandiIntro:
	.string "Agora… Deixe-me demonstrar o poder\n"
	.string "oculto dos Pokémon Psychic!$"

Route117_Text_BrandiDefeat:
	.string "Que massa!$"

Route117_Text_BrandiPostBattle:
	.string "Pokémon Psychic säo complexos.\n"
	.string "Você já capturou algum?$"

Route117_Text_AishaIntro:
	.string "Concentrar para ganhar.\n"
	.string "É assim que eu vou batalhar!$"

Route117_Text_AishaDefeat:
	.string "Näo perca tempo, indignado sobre\n"
	.string "uma perda - Eu prefiro treinar.$"

Route117_Text_AishaPostBattle:
	.string "Eu acho que se você se preocupar,\n"
	.string "em perder, será provável perder.$"

Route118_Text_RoseIntro:
	.string "O aroma das flores tem uma mágica\n"
	.string "potência. Ele purifica corpo e alma.$"

Route118_Text_RoseDefeat:
	.string "Oh, meu Deus.\n"
	.string "Eu perdi mesmo.$"

Route118_Text_RosePostBattle:
	.string "Flores, Pokémon…\n"
	.string "Eu amo o que cheira bem.\p"
	.string "Fedores…\n"
	.string "Ah, Eu deixo passar.$"

Route118_Text_RoseRegister:
	.string "Eu quero muito batalhar outra vez…\n"
	.string "Vamos nos registrar, ok?$"

Route118_Text_RoseRematchIntro:
	.string "Você veio até aqui só pelo\n"
	.string "doce aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "O poder do aroma…\n"
	.string "Näo consegue fazer muito.$"

Route118_Text_RosePostRematch:
	.string "Se você usar um aroma doce adequado,\n"
	.string "Pokémon será atraído por ele.$"

Route118_Text_PerryIntro:
	.string "Pokémon Fly voam elegantemente\n"
	.string "no céu… Eles säo os melhores!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "Eu perdi…$"

Route118_Text_PerryPostBattle:
	.string "Você tem bons Pokémon.\n"
	.string "Vou ter que treinar melhor o meu.$"

Route118_Text_ChesterIntro:
	.string "Prepare o vôo!\n"
	.string "Meus Pokémon!$"

Route118_Text_ChesterDefeat:
	.string "Eles tentaräo voar…$"

Route118_Text_ChesterPostBattle:
	.string "Se eles ficarem fortes, eles podem\n"
	.string "voar mais livremente…$"

Route118_Text_BarnyIntro:
	.string "Sou um pescador e também um treinador.\n"
	.string "Estou feliz com meus Pokémon.$"

Route118_Text_BarnyDefeat:
	.string "Eu pensei que estava bom meu\n"
	.string "treinamento…$"

Route118_Text_BarnyPostBattle:
	.string "Eu näo ganharia porque näo treino\n"
	.string "muito os meus Pokémon…\p"
	.string "Ah! Eu só pescava, entende?$"

Route118_Text_WadeIntro:
	.string "Para pescadores, o equipamento\p"
	.string "é tudo. Mas para os treinadores,\n"
	.string "temos Pokémon e coraçäo, é claro! $"

Route118_Text_WadeDefeat:
	.string "Ai, Ai… meu coraçäo?$"

Route118_Text_WadePostBattle:
	.string "Pense bem nisso, a pesca é uma batalha\n"
	.string "entre um pescador e um Pokémon.$"

Route118_Text_DaltonIntro:
	.string "Escute a melodia da cançäo!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Uma guitarra elétrica nem sempre\n"
	.string "tem que ser ruidosa…\p"
	.string "Ela pode ser muito bem tocada\n"
	.string "com melodias para o coraçäo…$"

Route118_Text_DaltonRegister:
	.string "Quando eu compor outras melodias,\n"
	.string "você tem que vim ouvir, Ok.$"

Route118_Text_DaltonRematchIntro:
	.string "A melodia do meu Pokémon e eu…\n"
	.string "Vamos conquistar à sua alma.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Ao tocar, minhas emoçöes chega até\n"
	.string "você por minha guitarra elétrica…$"

Route118_Text_DeandreIntro:
	.string "Vá, vá, vái!\n"
	.string "Pokémon 1, 2, e 3!$"

Route118_Text_DeandreDefeat:
	.string "Oh meus Pokémon! Vocês estäo bem?\n"
	.string "Pokémon 1, 2, e 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Näo é legal? Eu e meus Pokémon\n"
	.string "somos uma equipe.\p"
	.string "Você pode copiar eu näo ligo.$"

Route119_Text_BrentIntro:
	.string "Somos o Mimic Circle!\n"
	.string "Vamos imitar você!$"

Route119_Text_BrentDefeat:
	.string "O que…\n"
	.string "Eu perdi!$"

Route119_Text_BrentPostBattle:
	.string "O que é ser um mímico?\p"
	.string "Fufufu…\n"
	.string "Você nunca vai entender…$"

Route119_Text_DonaldIntro:
	.string "Entäo, nos encontramos!\n"
	.string "Meus Pokémon insetos e companhia!$"

Route119_Text_DonaldDefeat:
	.string "Näo quero te ver mais…$"

Route119_Text_DonaldPostBattle:
	.string "Eu quero imitá-lo um pouco mais.\n"
	.string "Você poderia se mover?$"

Route119_Text_TaylorIntro:
	.string "Se você anda, dou um passo a frente.\p"
	.string "Se vira à direita, eu também…$"

Route119_Text_TaylorDefeat:
	.string "Você ganhou, eu perdi…$"

Route119_Text_TaylorPostBattle:
	.string "Eu näo consegui imitá-lo na batalha.\n"
	.string "Isso é impossível…\l"
	.string "Isso me deixa irritado…$"

Route119_Text_DougIntro:
	.string "Sim, você me pegou!\n"
	.string "Ou você estava tentando me evitar?$"

Route119_Text_DougDefeat:
	.string "Nossa… foi uma ótima batalha!$"

Route119_Text_DougPostBattle:
	.string "Somos o Mimic Circle!\n"
	.string "Espero que você aprecie a diversäo.$"

Route119_Text_GregIntro:
	.string "Você sabe quem eu sou?\p"
	.string "Mas, eu também näo conheço você.\n"
	.string "Entäo, vamos lutar!$"

Route119_Text_GregDefeat:
	.string "Você é muito forte!$"

Route119_Text_GregPostBattle:
	.string "Até que você fuja, vamos continuar\n"
	.string "imitando cada movimento seu.$"

Route119_Text_KentIntro:
	.string "O Mimic Circle é formado por pessoas\n"
	.string "que gostam da arte da mímica.\p"
	.string "A batalha começa se encontrados!$"

Route119_Text_KentDefeat:
	.string "Eu desisto!$"

Route119_Text_KentPostBattle:
	.string "Bora, junte-se ao Mimic Circle.$"

Route119_Text_JacksonIntro:
	.string "Quem tem o conhecimento e\n"
	.string "a técnica de sobrevivência?\p"
	.string "Pokémon Rangers, é quem tem!$"

Route119_Text_JacksonDefeat:
	.string "Eu näo tinha muitos Pokémon\n"
	.string "Que pena…$"

Route119_Text_JacksonPostBattle:
	.string "Para romper com a civilizaçäo e\n"
	.string "despertar o espírito selvagem!\p"
	.string "Essa é a nossa visäo.$"

Route119_Text_JacksonRegister:
	.string "Eu espero ter uma revanche sem zombar\n"
	.string "da minha falta de conhecimento.$"

Route119_Text_JacksonRematchIntro:
	.string "Vou recuperar meu espírito selvagem\n"
	.string "por estar junto com Pokémon.$"

Route119_Text_JacksonRematchDefeat:
	.string "Você manteve-se forte!$"

Route119_Text_JacksonPostRematch:
	.string "Acredite em seus Pokémon.\n"
	.string "Acredite em si mesmo.\p"
	.string "A estrada vai se revelar a você.$"

Route119_Text_CatherineIntro:
	.string "Oh? Olhe para você.\p"
	.string "Para quem gosta de aventura,\n"
	.string "você deve está viajando muito.$"

Route119_Text_CatherineDefeat:
	.string "Os acidentes acontecem\n"
	.string "se ficar desatento!$"

Route119_Text_CatherinePostBattle:
	.string "Coragem…\n"
	.string "Você está viajando?\p"
	.string "Mas você já tem tudo que você precisa.\n"
	.string "Mentalmente e fisicamente bem.$"

Route119_Text_CatherineRegister:
	.string "Você tem uma Pokénav?\n"
	.string "É uma ferramenta indispensável\p"
	.string "para o treinador.\n"
	.string "Vamos registrar os contatos, entäo! $"

Route119_Text_CatherineRematchIntro:
	.string "Como vai sua jornada com\n"
	.string "seus Pokémon?$"

Route119_Text_CatherineRematchDefeat:
	.string "Ainda me falta alguma coisa…$"

Route119_Text_CatherinePostRematch:
	.string "Você sendo um Treinador Pokémon,\n"
	.string "confie nos seus Pokémon, entäo eles\l"
	.string "confiaram em você.$"

Route119_Text_HughIntro:
	.string "O vasto céu é uma coisa indescritível!\p"
	.string "Nada pode se comparar à pura\n"
	.string "alegria de poder voar.$"

Route119_Text_HughDefeat:
	.string "Que queda!$"

Route119_Text_HughPostBattle:
	.string "Meu Pokémon fez meu sonho de\n"
	.string "voar virá realidade.$"

Route119_Text_PhilIntro:
	.string "Eu vou te mostrar o verdadeiro\n"
	.string "potencial do meu Pokémon!$"

Route119_Text_PhilDefeat:
	.string "Faltou potencial…$"

Route119_Text_PhilPostBattle:
	.string "Desde que eu era criança, eu sempre\n"
	.string "admiro Pokémon pássaros…$"

Route119_Text_YasuIntro:
	.string "Eu me escondo nas sombras, e vivo em\n"
	.string "trevas… Esse é o meu destino.\p"
	.string "Eu vim desafiar você!$"

Route119_Text_YasuDefeat:
	.string "Admito perder!$"

Route119_Text_YasuPostBattle:
	.string "Os derrotados na batalha foge\n"
	.string "e volta para as sombras.\l"
	.string "Esse, também, é o meu destino…$"

Route119_Text_TakashiIntro:
	.string "Se você estiver em guarda,\n"
	.string "você terá um pouco de dor.$"

Route119_Text_TakashiDefeat:
	.string "Você é simplismente bom!$"

Route119_Text_TakashiPostBattle:
	.string "Meu ataque surpresa falhou feio…$"

Route119_Text_HideoIntro:
	.string "Estou fantasiado de árvore!$"

Route119_Text_HideoDefeat:
	.string "Admito sua superioridade.$"

Route119_Text_HideoPostBattle:
	.string "Gosto de ser uma árvore na floresta!\n"
	.string "Queria ser um Pokémon, também!\p"
	.string "Näo há nenhum significado profundo.$"

Route119_Text_ChrisIntro:
	.string "Você falou comigo…?\n"
	.string "Entäo você quer me desafiar?\p"
	.string "Claro! Vou testar o Pokémon que\n"
	.string "eu peguei Surfando!$"

Route119_Text_ChrisDefeat:
	.string "Näo tenho a menor idéia…\n"
	.string "Como faço para ganhar.$"

Route119_Text_ChrisPostBattle:
	.string "Vou surfar no meu Pokémon…\p"
	.string "Entäo vou pescar por aí…\p"
	.string "É indescritível e luxuriante!$"

Route119_Text_FabianIntro:
	.string "Vou acertar um acorde de energia!\n"
	.string "E a vitória é minha!\l"
	.string "É hora de brilhar, yeah!$"

Route119_Text_FabianDefeat:
	.string "Você me mostrou quem é o CHEFE!\n"
	.string "Ok, vou aceitar minha derrota!$"

Route119_Text_FabianPostBattle:
	.string "Ai… você me acertou!\n"
	.string "Deixe-me em paz.\l"
	.string "Agora… Você ganhou mais experiência.$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\n"
	.string "Olha só um Treinador miúdo.\l"
	.string "Vamos batalhar!$"

Route119_Text_DaytonDefeat:
	.string "Você é muito incrível!\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"
	.string "Vou tentar respeitar os treinadores!\l"
	.string "Hohoho! $"

Route119_Text_RachelIntro:
	.string "Qualquer lugar que vou…\n"
	.string "Eu sempre levo o meu guarda-sol na mäo.$"

Route119_Text_RachelDefeat:
	.string "Ah…\n"
	.string "Isso näo é justo.$"

Route119_Text_RachelPostBattle:
	.string "Você pensa… meu guarda-sol é pesado?\n"
	.string "Sua BOLSA é cheia de lixo coisa que…\l"
	.string "Eu nunca transportaria.$"

Route120_Text_ColinIntro:
	.string "Você tem golpes que podem atingir\n"
	.string "um Pokémon voador?$"

Route120_Text_ColinDefeat:
	.string "Você sabe o que faz!$"

Route120_Text_ColinPostBattle:
	.string "O golpe Fly é bem conveniente,\n"
	.string "você näo acha?\p"
	.string "Quando o Pokémon está voando,\n"
	.string "quase nenhum golpe pode acertar.$"

Route120_Text_RobertIntro:
	.string "Meu Pokémon é forte!\n"
	.string "Como está o seu?$"

Route120_Text_RobertDefeat:
	.string "Seus Pokémon estäo fortes…$"

Route120_Text_RobertPostBattle:
	.string "Um Pokémon que cresce bem,\n"
	.string "sempre você pode contar.$"

Route120_Text_RobertRegister:
	.string "Você pode ser um dos melhores aqui.\n"
	.string "Eu quero te registrar na minha Pokénav!$"

Route120_Text_RobertRematchIntro:
	.string "Um Pokémon que cresce bem,\n"
	.string "sempre você pode contar.$"

Route120_Text_RobertRematchDefeat:
	.string "Seus Pokémon estäo super fortes.$"

Route120_Text_RobertPostRematch:
	.string "Meus Pokémon crescem fortes.\n"
	.string "Eu tenho que ficar forte, também.$"

Route120_Text_LorenzoIntro:
	.string "Vou verificar o seu Pokémon e ver\n"
	.string "se estäo aptos para batalhar.$"

Route120_Text_LorenzoDefeat:
	.string "Que Pokémon forte, você näo corre\n"
	.string "perigo nem precisa de resgate.$"

Route120_Text_LorenzoPostBattle:
	.string "Viajar para onde seu coraçäo deseje\n"
	.string "com Pokémon…\l"
	.string "Essa é a alegria de ser um treinador.$"

Route120_Text_JennaIntro:
	.string "Como está o seu condicionamento físico?\n"
	.string "Se näo está bem…\l"
	.string "Você pode ficar em situaçöes críticas.$"

Route120_Text_JennaDefeat:
	.string "Estou em forma, mas…$"

Route120_Text_JennaPostBattle:
	.string "Fitness está na minha rotina.\n"
	.string "Eu sempre corro com meus Pokémon.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Quer batalhar?$"

Route120_Text_JeffreyDefeat:
	.string "Perdi…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Treinarei mais…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Você tem uma Pokénav…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Quer lutar novamente?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Perdi de novo…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Treinarei mais…\l"
	.string "Pelo o meu precioso Pokémon inseto…$"

Route120_Text_JenniferIntro:
	.string "Pokémon têm habilidades especiais.\n"
	.string "Se você quer se tornar o melhor\l"
	.string "treinador, aprenda sobre elas.$"

Route120_Text_JenniferDefeat:
	.string "Você está pensando em que?$"

Route120_Text_JenniferPostBattle:
	.string "As habilidades especiais do Pokémon\n"
	.string "faz a diferença dos estilos.$"

Route120_Text_ChipIntro:
	.string "Quem é você?\p"
	.string "Você talvez procura por antigas ruínas\n"
	.string "dizem que säo rumores. Eu acho…\l"
	.string "Que ela existe segundo a lenda?$"

Route120_Text_ChipDefeat:
	.string "Que retrocesso vergonhoso…$"

Route120_Text_ChipPostBattle:
	.string "Essa rocha gigante… Quero acreditar\n"
	.string "que ela pode ser as ruínas.\l"
	.string "Mas näo vejo nenhuma entrada.$"

Route120_Text_ClarissaIntro:
	.string "Por que eu carrego este guarda-sol?\p"
	.string "Eu vou te dizer se você ganhar, ok.$"

Route120_Text_ClarissaDefeat:
	.string "O guarda-sol näo afastar ataques\n"
	.string "Pokémon…$"

Route120_Text_ClarissaPostBattle:
	.string "Eu näo acho que sol forte é bom\n"
	.string "para o meu Pokémon.\l"
	.string "Eu protejo com o meu guarda-sol.$"

Route120_Text_AngelicaIntro:
	.string "Eu, Pokémon, e meu guarda-sol…\p"
	.string "Se qualquer um deles estiver ausente,\n"
	.string "minha beleza fica arruinada.$"

Route120_Text_AngelicaDefeat:
	.string "Você arruinou 100% a minha beleza…$"

Route120_Text_AngelicaPostBattle:
	.string "Um guarda-sol näo combina com você.\p"
	.string "Por que, algo assim só vai\n"
	.string "atrapalha o seu caminho.$"

Route120_Text_KeigoIntro:
	.string "Vou adotar os golpes dos Pokémon\n"
	.string "e criar novas técnicas ninja.$"

Route120_Text_KeigoDefeat:
	.string "A criaçäo de novas técnicas ninja\n"
	.string "é apenas um sonho ainda…$"

Route120_Text_KeigoPostBattle:
	.string "Talvez eu devesse aprender sobre\n"
	.string "um ninja sensei.$"

Route120_Text_RileyIntro:
	.string "Nós ninja escondemos em nossa\n"
	.string "capa camuflada. Aposto que\l"
	.string "näo sabia onde eu estava.!$"

Route120_Text_RileyDefeat:
	.string "Perdi!\n"
	.string "Vou camuflar minha vergonha!$"

Route120_Text_RileyPostBattle:
	.string "A minha camuflagem\n"
	.string "é toda artesanal.$"

Route120_Text_CallieIntro:
	.string "Se você näo prestar atençäo,\n"
	.string "pode-se machucar!$"

Route120_Text_CallieDefeat:
	.string "Eu fui a única a se machucar.$"

Route120_Text_CalliePostBattle:
	.string "Pergunto-me… Evoluo meus Pokémon?\n"
	.string "Säo bonitos do jeito que säo, mas…$"

Route120_Text_LeonelIntro:
	.string "Ei? Sua equipe de Pokémon,…\n"
	.string "tem tipos diferentes?$"

Route120_Text_LeonelDefeat:
	.string "Eu vi a sua equipe em açäo!$"

Route120_Text_LeonelPostBattle:
	.string "Acho incrível você é täo forte lutando\n"
	.string "com o seu Pokémon favorito.$"

Route121_Text_VanessaIntro:
	.string "Você vai ver o Pokémon mais lindo?\n"
	.string "É só emoçöes…$"

Route121_Text_VanessaDefeat:
	.string "Eu nem sei o que dizer!$"

Route121_Text_VanessaPostBattle:
	.string "Vou para uma competiçäo em Lilycove.\p"
	.string "Meus Pokémon väo passar sem\n"
	.string "problemas pelo Master Class.$"

Route121_Text_WalterIntro:
	.string "Com meu Pokémon…\n"
	.string "Eu viajei aos 4 cantos do mundo.\p"
	.string "Você pode dizer que tenho alguma\n"
	.string "confiança em minhas habilidades.$"

Route121_Text_WalterDefeat:
	.string "Ah, bom combate.$"

Route121_Text_WalterPostBattle:
	.string "Queria dar a volta ao mundo, mais\n"
	.string "uma vez com o meu Pokémon.$"

Route121_Text_WalterRegister:
	.string "Sua proeza com Pokémon é notável.\n"
	.string "Permita-me registá-lo como lembrança.$"

Route121_Text_WalterRematchIntro:
	.string "Com o meu Pokémon, eu viajei\n"
	.string "pelos 4 cantos do mundo.\p"
	.string "Pode dizer que tenho alguma confiança\n"
	.string "em minhas habilidades.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bom combate.$"

Route121_Text_WalterPostRematch:
	.string "O seu Pokémon e você…\p"
	.string "Seu talento juntos será considerado\n"
	.string "forte mesmo no exterior.$"

Route121_Text_TammyIntro:
	.string "Há poderes muito além da nossa\n"
	.string "compreensäo neste mundo…$"

Route121_Text_TammyDefeat:
	.string "Perdi feio…$"

Route121_Text_TammyPostBattle:
	.string "Mt. Pyre… Há um poder misterioso\n"
	.string "na atmosfera de lá…$"

Route121_Text_KateIntro:
	.string "Kate: Juntas, näo temos medo algum!\n"
	.string "Vamos demonstrar nossa força!$"

Route121_Text_KateDefeat:
	.string "Kate: Eu estraguei tudo na frente\n"
	.string "da minha parceira…$"

Route121_Text_KatePostBattle:
	.string "Kate: Quando alguém está confiando\n"
	.string "em mim, tenho que parecer legal na\l"
	.string "frente dela…$"

Route121_Text_KateNotEnoughMons:
	.string "Kate: Se você só tem 1 Pokémon,\n"
	.string "nós näo podemos lutar com você.\p"
	.string "Isso seria bullying.$"

Route121_Text_JoyIntro:
	.string "Joy: Juntas, näo temos medo!\n"
	.string "Vamos demonstrar o nosso estilo!$"

Route121_Text_JoyDefeat:
	.string "Joy: Snif… me perdoe, Kate!$"

Route121_Text_JoyPostBattle:
	.string "Joy: Ehehe, eu vou treinar com Kate\n"
	.string "minha parceira escolar, ela é a melhor.$"

Route121_Text_JoyNotEnoughMons:
	.string "Joy: Você precisa no mínimo 2 Pokémon\n"
	.string "se você deseja nos desafiar.$"

Route121_Text_JessicaIntro:
	.string "Pare aí\n"
	.string "Olhe bem para o meu precioso Pokémon!$"

Route121_Text_JessicaDefeat:
	.string "Ah, como você se atreve.\n"
	.string "Näo seja täo sério.$"

Route121_Text_JessicaPostBattle:
	.string "Talvez eu vá pegar mais Pokémon\n"
	.string "na Safari Zone.$"

Route121_Text_JessicaRegister:
	.string "Foi fácil para você neste momento.\n"
	.string "Näo vai ser assim na próxima vez.$"

Route121_Text_JessicaRematchIntro:
	.string "Meu precioso Pokémon cresceu!\n"
	.string "Venha olhar!$"

Route121_Text_JessicaRematchDefeat:
	.string "Ah, como você se atreve…\n"
	.string "Você ainda pegou leve.$"

Route121_Text_JessicaPostRematch:
	.string "Talvez eu vá capturar mais\n"
	.string "Pokémon lá no Safari Zone.$"

Route121_Text_CristinIntro:
	.string "Eu tenho essa rotina.\n"
	.string "Derrotar 5 treinadores por dia.\l"
	.string "Olha… Você é o número 5!$"

Route121_Text_CristinDefeat:
	.string "Você é horrível!$"

Route121_Text_CristinPostBattle:
	.string "Näo queria perder facilmente…\n"
	.string "Vou ganhar na próxima vez.$"

Route121_Text_CristinRegister:
	.string "Isso foi humilhaçäo total!\n"
	.string "Eu näo vou esquecer…\l"
	.string "Anota na sua Pokénav!$"

Route121_Text_CristinRematchIntro:
	.string "Tenho essa nova rotina.\n"
	.string "Derrotar 10 treinadores por dia.\l"
	.string "Adivinha? Você é o nº 10.$"

Route121_Text_CristinRematchDefeat:
	.string "Espere! Espere!\n"
	.string "Eu exijo uma revanche!$"

Route121_Text_CristinPostRematch:
	.string "Um adversário que näo pude vencer…\n"
	.string "Snivel…\l"
	.string "Eu näo consigo acreditar nisso…$"

Route121_Text_CaleIntro:
	.string "Você näo pode ver mas eu tenho\n"
	.string "muitas coisas comigo?\p"
	.string "E você ainda insiste em\n"
	.string "a gente batalhar?$"

Route121_Text_CaleDefeat:
	.string "É claro que eu perdi!\n"
	.string "Estou com as mäos ocupadas.$"

Route121_Text_CalePostBattle:
	.string "Eu comprei muita coisa em\n"
	.string "uma loja de Lilycove.\p"
	.string "Essa estrada leva até lá.\n"
	.string "Queria ter uma bolsa igual a sua.$"

Route121_Text_MylesIntro:
	.string "Näo há nada que eu amo mais do que\n"
	.string "bisbilhotar os Pokémon dos outros!$"

Route121_Text_MylesDefeat:
	.string "Que… incrível!$"

Route121_Text_MylesPostBattle:
	.string "Eles säo ótimos, seus Pokémon!\n"
	.string "Como você cria eles?$"

Route121_Text_PatIntro:
	.string "Quero que o mundo veja o Pokémon…\n"
	.string "Que eu peguei!$"

Route121_Text_PatDefeat:
	.string "Uau!\n"
	.string "Espetacular!$"

Route121_Text_PatPostBattle:
	.string "Treino todos os Pokémon com o mesmo\n"
	.string "amor e carinho - näo tenho favoritos.$"

Route121_Text_MarcelIntro:
	.string "Meus Pokémon nunca provou derrota!\n"
	.string "Na próxima vitória, vou escreve-lós\l"
	.string "nos Contests.$"

Route121_Text_MarcelDefeat:
	.string "Ah, o que aconteceu aqui?$"

Route121_Text_MarcelPostBattle:
	.string "Eu tenho que treinar mais antes\n"
	.string "de entrar em qualquer competiçäo.$"

Route123_Text_WendyIntro:
	.string "Quero ver o quanto você é forte?\n"
	.string "E te digo agora mesmo!$"

Route123_Text_WendyDefeat:
	.string "Você passou com distinçäo!$"

Route123_Text_WendyPostBattle:
	.string "Sua força é maravilhosa…\n"
	.string "É melhor do que eu!$"

Route123_Text_BraxtonIntro:
	.string "Parece ter uma grande coleçäo\n"
	.string "de insignias de ginásio.\p"
	.string "Hm… Deixe-me ver se você\n"
	.string "realmente as merece!$"

Route123_Text_BraxtonDefeat:
	.string "Sim, você ganhou por merecer!$"

Route123_Text_BraxtonPostBattle:
	.string "Suas insignias deixa\n"
	.string "um orgulho em você!"

Route123_Text_VioletIntro:
	.string "Falam que os tempos bons tem\n"
	.string "cheiro de aromas bons.$"

Route123_Text_VioletDefeat:
	.string "Oh… Sentir o cheiro amargo\n"
	.string "da miséria…$"

Route123_Text_VioletPostBattle:
	.string "O jardim do Berry Master tem\n"
	.string "muitas fragrâncias edificantes.$"

Route123_Text_CameronIntro:
	.string "Poderes psíquicos requer força\p"
	.string "de vontade. Näo tenho vontade\n"
	.string "de perder, por isso sou forte!$"

Route123_Text_CameronDefeat:
	.string "Tô triste…$"

Route123_Text_CameronPostBattle:
	.string "Poderes psíquicos requer força de\n"
	.string "vontade. Nunca pensei que perderia…$"

Route123_Text_CameronRegister:
	.string "Sinto que…\n"
	.string "Você e eu lutaremos de novo.!\l"
	.string "Só näo posso prever se vou ganhar…\p"
	.string "Registre na sua Pokénav!"

Route123_Text_CameronRematchIntro:
	.string "Eu me convencer de que eu näo vou\n"
	.string "perder mais. Isso me faz mais forte!$"

Route123_Text_CameronRematchDefeat:
	.string "Tô triste…$"

Route123_Text_CameronPostRematch:
	.string "Deveria treinar no Mt Pyre…\n"
	.string "Senäo eu nunca te vencerei.$"

Route123_Text_JackiIntro:
	.string "Näo fique muito feliz se o seu Pokémon\n"
	.string "aprender poderes psíquicos.\p"
	.string "Conheça os poderes para torná-los\n"
	.string "realmente útil.$"

Route123_Text_JackiDefeat:
	.string "Uau… gostei.$"

Route123_Text_JackiPostBattle:
	.string "Todos temos poderes psíquicos…\n"
	.string "Apenas näo sei bem como usá-los.$"

Route123_Text_JackiRegister:
	.string "Eu quero uma revanche novamente.\n"
	.string "O que você me diz?$"

Route123_Text_JackiRematchIntro:
	.string "Já despertou os poderes\n"
	.string "psíquicos em você?$"

Route123_Text_JackiRematchDefeat:
	.string "Incrível!$"

Route123_Text_JackiPostRematch:
	.string "Seu poder com Pokémon…\n"
	.string "Pode ser um poder psíquico também.$"

Route123_Text_MiuIntro:
	.string "Miu: Olá, Espero que o seu Pokémon\n"
	.string "näo vai chorar quando perder.$"

Route123_Text_MiuDefeat:
	.string "Miu: Ui… perdemos.$"

Route123_Text_MiuPostBattle:
	.string "Miu: Nossa seus Pokémon säo fortes,\n"
	.string "porque vocês säo amigos.$"

Route123_Text_MiuNotEnoughMons:
	.string "Miu: Näo é divertido batalhar,\n"
	.string "se você näo tiver 2 Pokémon.$"

Route123_Text_YukiIntro:
	.string "Yuki: Hehehe! Veja somos mais\n"
	.string "forte do que você.$"

Route123_Text_YukiDefeat:
	.string "Yuki: Aff… perdemos.$"

Route123_Text_YukiPostBattle:
	.string "Yuki: Por que você é täo forte?\n"
	.string "Nunca perdemos antes.$"

Route123_Text_YukiNotEnoughMons:
	.string "Yuki: Näo é divertido batalhar,\n"
	.string "se você näo tiver 2 Pokémon.$"

Route123_Text_KindraIntro:
	.string "Mt. Pyre… Onde dorme os\n"
	.string "espíritos dos Pokémon…\l"
	.string "e os seus também dorme?$"

Route123_Text_KindraDefeat:
	.string "Poxa… quanta vitalidade…!!$"

Route123_Text_KindraPostBattle:
	.string "Mt. Pyre… Onde dorme os\n"
	.string "espíritos dos Pokémon…\p"
	.string "Lá deve haver algum poder que\n"
	.string "acalma os espíritos…$"

Route123_Text_FernandoIntro:
	.string "Eu vou eletrificar você, enquanto\n"
	.string "toco essa melodia!$"

Route123_Text_FernandoDefeat:
	.string "Ei, calma ai!\n"
	.string "Eu ainda estava na introduçäo.$"

Route123_Text_FernandoPostBattle:
	.string "Você é rocha firme.\n"
	.string "Vou escrever uma cançäo sobre você.$"

Route123_Text_FernandoRegister:
	.string "Na próxima vez escute a música\n"
	.string "completa, você vai ouvir?$"

Route123_Text_FernandoRematchIntro:
	.string "É hoje que farei isso!\n"
	.string "Mas antes, apagarei as luzes\l"
	.string "e assim finalizarei meu som.!$"

Route123_Text_FernandoRematchDefeat:
	.string "Ei, espere!\n"
	.string "Eu nem sequer cantei o refräo!$"

Route123_Text_FernandoPostRematch:
	.string "Achei que estava encantado\n"
	.string "por minha música, se perdeu?$"

Route123_Text_DavisIntro:
	.string "Este é o meu Pokémon inseto!\n"
	.string "Meu irmäo mais velho me deu ele.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "Waaaah, Waaaah!$"

Route123_Text_DavisPostBattle:
	.string "Näo diga a meu irmäo que eu perdi.\n"
	.string "Guarde este segredo, ok!?$"

Route123_Text_JazmynIntro:
	.string "Minha confiança vai aumentar lutando\n"
	.string "com alguém obviamente forte.$"

Route123_Text_JazmynDefeat:
	.string "Lá vai a minha confiança…$"

Route123_Text_JazmynPostBattle:
	.string "Dizem que você näo deve julgar uma\n"
	.string "pessoa por sua aparência.\p"
	.string "Mas, seus olhares näo mentem…$"

Route123_Text_FrederickIntro:
	.string "Olá, criança!\n"
	.string "Você tem algum tempinho?$"

Route123_Text_FrederickDefeat:
	.string "Ah, uma criança muito capaz!\n"
	.string "Deixe-me contribuir com sua mesada.$"

Route123_Text_FrederickPostBattle:
	.string "Colaborei com sua mesada?\n"
	.string "O dinheiro do prêmio é suficiente?$"

Route123_Text_AlbertoIntro:
	.string "Devo reconhecer: Pokémon\n"
	.string "pássaro säo minha obsessäo!\p"
	.string "Pássaros säo legais!\n"
	.string "Säo os melhores!$"

Route123_Text_AlbertoDefeat:
	.string "Perdi mas, os Pokémon\n"
	.string "Pássaros säo legais!$"

Route123_Text_AlbertoPostBattle:
	.string "Percebi penas de Pokémon Pássaros\n"
	.string "que soltam durante as batalhas.\p"
	.string "Eu vou fazer um chapéu com\n"
	.string "penas de Pokémon Pássaros.$"

Route123_Text_EdIntro:
	.string "Quando näo vejo treinadores,\n"
	.string "deixo os meus Pokémon batalhar\l"
	.string "entre si. Eu os observo.$"

Route123_Text_EdDefeat:
	.string "Eu gostei dos seus Pokémon.$"

Route123_Text_EdPostBattle:
	.string "Hehehe… Penso em usar suas táticas!\n"
	.string "Acho que vai me ajudar a melhorar.$"

Route123_Text_JonasIntro:
	.string "EMBOSCADA…!\n"
	.string "E um Treinador caiu na minha armadilha!$"

Route123_Text_JonasDefeat:
	.string "Se você näo perder, como eu vou\n"
	.string "me divertir brincando de ninja?$"

Route123_Text_JonasPostBattle:
	.string "Eu vou fazer outra EMBOSCADA para\n"
	.string "o próximo treinador.$"

Route123_Text_KayleyIntro:
	.string "Acabei comprando este guarda-chuva…\n"
	.string "Eu gosto de proteger a pele.$"

Route123_Text_KayleyDefeat:
	.string "Você é melhor do que eu\n"
	.string "cerca de 5 vezes!$"

Route123_Text_KayleyPostBattle:
	.string "O uso de acessórios de forma eficaz\n"
	.string "é o segredo por trás da moda.$"

Route124_Text_SpencerIntro:
	.string "Ei, você se perdeu?\p"
	.string "Se ganhar de meus Pokémon, te\n"
	.string "ajudarei a encontrar o norte.$"

Route124_Text_SpencerDefeat:
	.string "Eu perdi meu rumo na batalha!$"

Route124_Text_SpencerPostBattle:
	.string "Muitas pessoas perdem o rumo no mar.\p"
	.string "Se você é desse tipo, você deve\n"
	.string "consultar o mapa da Pokénav.$"

Route124_Text_RolandIntro:
	.string "Quê! Monta em um Pokémon,\n"
	.string "assim näo precisa nadar…\p"
	.string "Nossa! Que preguiça!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "É sério…$"

Route124_Text_RolandPostBattle:
	.string "Estou ficando errugado… Fico\n"
	.string "bastante tempo na água… Se\p"
	.string "pudesse montar um Pokémon igual a tú…$"

Route124_Text_JennyIntro:
	.string "Se te pega boiando no mar assim,\n"
	.string "os Pokémon vem brincar com você.$"

Route124_Text_JennyDefeat:
	.string "Oh… Que pena…\n"
	.string "Perdida no mar.$"

Route124_Text_JennyPostBattle:
	.string "Nadando, nadando, percebi que há\n"
	.string "Pokémon que atacam, menos que\p"
	.string "outros. Se vê que cada Pokémon\n"
	.string "tem personalidade próprias.$"

Route124_Text_JennyRegister:
	.string "Eu tenho um capricho: quero que\n"
	.string "me registre em sua Pokénav.$"

Route124_Text_JennyRematchIntro:
	.string "Se te pega boiando no mar assim,\n"
	.string "os treinadores desafiam você!$"

Route124_Text_JennyRematchDefeat:
	.string "Que raro…\n"
	.string "Eu voltei a perder…$"

Route124_Text_JennyPostRematch:
	.string "Näo é que tenha nada que ver, mas\n"
	.string "acho que vou visitar a Trick House.$"

Route124_Text_GraceIntro:
	.string "Estou ficando cansada de nadar…\n"
	.string "Vamos uma batalha?$"

Route124_Text_GraceDefeat:
	.string "Näo tinha idéia de como\n"
	.string "você era forte!$"

Route124_Text_GracePostBattle:
	.string "Todo o esforço que você faz\n"
	.string "deixa você muito mais forte.$"

Route124_Text_ChadIntro:
	.string "Hahahaha… Eu mergulho até o fundo\n"
	.string "para que nada me veja.\l"
	.string "Aqui eu sou o melhor em mergulho!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "Eu afundei…$"

Route124_Text_ChadPostBattle:
	.string "Quer uma boa dica de onde fazer\n"
	.string "mergulho e nas mancha por aqui.\p"
	.string "Estou pegando folêgo para entrar ali…$"

Route124_Text_LilaIntro:
	.string "Lila: Ai…\p"
	.string "Aqui estou, no meio do mar, e com\n"
	.string "quem? Com meu irmäozinho!\p"
	.string "Estou täo estressada tenho\n"
	.string "que lutar com alguém!$"

Route124_Text_LilaDefeat:
	.string "Lila: Roy! Perdemos por culpa\n"
	.string "sua. Está sempre atrasado.$"

Route124_Text_LilaPostBattle:
	.string "Lila: Ai…\p"
	.string "Se em vez de estar com meu irmäozinho,\n"
	.string "estivesse com um bom namorado…$"

Route124_Text_LilaNotEnoughMons:
	.string "Lila: Ei, você quer nos desafiar?\n"
	.string "Só poderá se você tiver 2 Pokémon.$"

Route124_Text_RoyIntro:
	.string "Roy: Minha irmä  mais velha e a\p"
	.string "rainha dos Pokémon. Agora veja!$"

Route124_Text_RoyDefeat:
	.string "Roy: Ai…\n"
	.string "Minha irmä dirá que é culpa minha…$"

Route124_Text_RoyPostBattle:
	.string "Roy: Minha irmä é um pouco assustadora\n"
	.string "e dá medo quando zanga.\p"
	.string "Isso só por falta de um namorado…$"

Route124_Text_LilaRoyRegister:
	.string "Roy: Volte a batalhar conosco outra\n"
	.string "vez? Mas pegue leve com agente.$"

Route124_Text_RoyNotEnoughMons:
	.string "Roy: Ei, você quer nos desafiar?\n"
	.string "Traga 2 Pokémon, entäo.$"

Route124_Text_LilaRematchIntro:
	.string "Lila: Aaah…\p"
	.string "Aqui estou no mar, mas quem está comigo?\n"
	.string "Meu irmäo mais novo!\p"
	.string "Oh, oi, já faz um tempo. Vamos batalha\n"
	.string "entäo näo vou insistir sobre isso!$"

Route124_Text_LilaRematchDefeat:
	.string "Lila: Roy!\n"
	.string "A culpa é sua, perdemos de novo!\p"
	.string "Vamos ter um treinamento mais tarde!$"

Route124_Text_LilaPostRematch:
	.string "Lila: Aaaah…\p"
	.string "Queria um namorado, juntos venceríamos\n"
	.string "todos com lindas combinaçöes…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "Lila: Ei, você quer nos desafiar?\n"
	.string "Só poderá se você tiver 2 Pokémon.$"

Route124_Text_RoyRematchIntro:
	.string "Roy: Se nós perdemos, vou ficar triste.\n"
	.string "Estou perdido e sem rumo!$"

Route124_Text_RoyRematchDefeat:
	.string "Roy: Uh-oh…\n"
	.string "Minha irmä vai zangar comigo de novo.$"

Route124_Text_RoyPostRematch:
	.string "Roy: Minha irmä é realmente\n"
	.string "assustadora quando fica com raiva.\p"
	.string "Ela vai me fazer treinar muito\n"
	.string "com Pokémon depois…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "Roy: Ei, você quer nos desafiar?\n"
	.string "Traga 2 Pokémon, entäo.$"

Route124_Text_DeclanIntro:
	.string "Aqui estou, nadando na minha solidäo\n"
	.string "nesse enorme e bonito mar.\p"
	.string "Näo tem como eu descrever…\n"
	.string "Eu quero chorar.$"

Route124_Text_DeclanDefeat:
	.string "Que drepê…\n"
	.string "Maior que o enorme mar…$"

Route124_Text_DeclanPostBattle:
	.string "Vou procurar alguma nadadora\n"
	.string "que queira nadar um pouco comigo.$"

Route124_Text_IsabellaIntro:
	.string "Os surfistas me revolta.\n"
	.string "Acha que vai ganhar?$"

Route124_Text_IsabellaDefeat:
	.string "Näo! Näo estou chorando…\n"
	.string "É o doce dos meu olhos!$"

Route124_Text_IsabellaPostBattle:
	.string "Por aqui se encontra fraqmento\n"
	.string "de coisas de várias cores.$"

Route125_Text_NolenIntro:
	.string "Eu ouvi você se aproximar…\n"
	.string "Entäo, eu fui até você!$"

Route125_Text_NolenDefeat:
	.string "Surpreendeu!$"

Route125_Text_NolenPostBattle:
	.string "O som viaja mais rápido na água\n"
	.string "que no ar. Legal, né?$"

Route125_Text_StanIntro:
	.string "Ei, você aí!\n"
	.string "Veja o meu lindo Pokémon!$"

Route125_Text_StanDefeat:
	.string "Eu afundei…$"

Route125_Text_StanPostBattle:
	.string "Eu fui levado pelo encanto de\n"
	.string "Horsea, entäo comecei a nadar. $"

Route125_Text_TanyaIntro:
	.string "Estou cansada de nataçäo.\n"
	.string "Você pega uma batalha comigo?$"

Route125_Text_TanyaDefeat:
	.string "Você é demais!$"

Route125_Text_TanyaPostBattle:
	.string "Ufa…\n"
	.string "Qual é o caminho para Mossdeep?$"

Route125_Text_SharonIntro:
	.string "Está de bom humor para enfrentar\n"
	.string "o meu Pokémon do tipo Water?$"

Route125_Text_SharonDefeat:
	.string "Perdi…$"

Route125_Text_SharonPostBattle:
	.string "Uau… Seu poder… Você é real.\n"
	.string "Estou espantada!$"

Route125_Text_ErnestIntro:
	.string "Olá, jovem! Sou um marinheiro\n"
	.string "muito viajado. Um lobo do mar!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "Eu näo ganhei!$"

Route125_Text_ErnestPostBattle:
	.string "A maré sobe e desce no interior\n"
	.string "da Shoal Cave.\p"
	.string "Sabia que entre maré alta e a baixa\n"
	.string "há 6 horas de diferença?$"

Route125_Text_ErnestRegister:
	.string "Registre-me na sua Pokénav,\n"
	.string "e eu vou lhe dizer uma coisa boa.$"

Route125_Text_ErnestRematchIntro:
	.string "Hehe, está na hora da minha vingança.\n"
	.string "Vamos, vamos. Irei te esmagar!$"

Route125_Text_ErnestRematchDefeat:
	.string "Näo pude vencer!\n"
	.string "Näo pude vencer!$"

Route125_Text_ErnestRematchPostBattle:
	.string "A Shoal Cave…\p"
	.string "Há lugares que você poderá ou\n"
	.string "näo acessar de acordo com a maré.\l"
	.string "Hum, bem.\p"
	.string "A maré se alterna entre a maré\n"
	.string "baixa e alta a cada 6 horas.$"

Route125_Text_KimIntro:
	.string "Kim: Na Shoal Cave vive um\n"
	.string "velhinho engraçado. Alguém me disse.\l"
	.string "Vai visitá-lo, também?$"

Route125_Text_KimDefeat:
	.string "Kim: Pensei que iria vencer…$"

Route125_Text_KimPostBattle:
	.string "Kim: Na Shoal Cave vive um\n"
	.string "velhinho engraçado, verdade?\p"
	.string "Vamos lá vê-lo, Iris!$"

Route125_Text_KimNotEnoughMons:
	.string "Kim: Näo, näo, näo! Precisa ter\n"
	.string "2 Pokémon, se näo, näo vale!$"

Route125_Text_IrisIntro:
	.string "Iris: Kim, pode me dizer de uma\n"
	.string "vez aonde você deseja ir?$"

Route125_Text_IrisDefeat:
	.string "Iris: Oh, nós chegamos perto…$"

Route125_Text_IrisPostBattle:
	.string "Iris: Kim, quer ir mesmo\n"
	.string "na Shoal Cave?\l"
	.string "Veja que vamos nos molhar…$"

Route125_Text_IrisNotEnoughMons:
	.string "Iris: Näo, nunca jamais poderíamos ter\n"
	.string "um combate de 2 contra 1…$"

Route125_Text_PresleyIntro:
	.string "O que um ornitólogo como\n"
	.string "eu faz perdido por aqui?$"

Route125_Text_PresleyDefeat:
	.string "Ok, eu vou dizer o que faço aqui.$"

Route125_Text_PresleyPostBattle:
	.string "Coloquei uma mensagem em uma\n"
	.string "garrafa para o mar levar.\p"
	.string "É certo que encontrará\n"
	.string "uma nadadora!$"

Route125_Text_AuronIntro:
	.string "Ei, você aí! Foi você jogando\n"
	.string "lixo no mar, né?"

Route125_Text_AuronDefeat:
	.string "Nao! Näo, vejo que é uma\n"
	.string "pessoa super limpa.$"

Route125_Text_AuronPostBattle:
	.string "Eu vi uma garrafa asquerosa\n"
	.string "entre as ondas por aqui.\p"
	.string "Irrita-me muito quando alguém\n"
	.string "fica poluindo o mar!$"

Route126_Text_BarryIntro:
	.string "A nataçäo é o esporte completo.\n"
	.string "Te pöem em forma!$"

Route126_Text_BarryDefeat:
	.string "Admito!\n"
	.string "Você ganhou!$"

Route126_Text_BarryPostBattle:
	.string "Como meu corpo fica melhor a cada dia…\n"
	.string "Veja! Estou com o físico perfeito!$"

Route126_Text_DeanIntro:
	.string "Essa alta montanha de rocha\n"
	.string "branca é Sootopolis City.$"

Route126_Text_DeanDefeat:
	.string "Estou confuso?$"

Route126_Text_DeanPostBattle:
	.string "Eu näo encontro a entrada para\n"
	.string "Sootopolis. Onde pode estar?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "Nado como sereia!$"

Route126_Text_NikkiDefeat:
	.string "Minha fantasia afundou com a derrota!\n"
	.string "Glub, glub, glub…$"

Route126_Text_NikkiPostBattle:
	.string "Você me deixou triste… Queria\n"
	.string "ser levada pelo mar e sumir…$"

Route126_Text_BrendaIntro:
	.string "Olá, mequetrefe!\n"
	.string "Lutas contra mim?$"

Route126_Text_BrendaDefeat:
	.string "Oh, näooooo!$"

Route126_Text_BrendaPostBattle:
	.string "Amo brincar com os Pokémon\n"
	.string "saltando entre as ondas…$"

Route126_Text_PabloIntro:
	.string "Admire meu lindo corpo!\n"
	.string "Tenho mais músculos que um karateka! $"

Route126_Text_PabloDefeat:
	.string "Ops! Você é forte!\n"
	.string "Näo está mal! Nada mal!$"

Route126_Text_PabloPostBattle:
	.string "A derrota näo me desanima! Penso em\n"
	.string "treinar os meus Pokémon ainda mais!$"

Route126_Text_PabloRegister:
	.string "Ei, näo estava nada mal!\n"
	.string "Eu gostaria de te conhecer melhor!"

Route126_Text_PabloRematchIntro:
	.string "Observe meu lindo corpo!\n"
	.string "Sou uma maravilhosa nadadora!$"

Route126_Text_PabloRematchDefeat:
	.string "Oooops! Realmente forte!\n"
	.string "Nada mal! Nada mal!$"

Route126_Text_PabloPostRematch:
	.string "Vou treinar ainda mais!\n"
	.string "Você é um grande motivador!\l"
	.string "Ficarei no aguardo de uma revanche.!$"

Route126_Text_LeonardoIntro:
	.string "Näo faz muito tempo que aprendi a nadar,\n"
	.string "mas eu já sou um bom nadador.\p"
	.string "Näo há nada que me desafie.$"

Route126_Text_LeonardoDefeat:
	.string "UfA, desculpe eu deveria\n"
	.string "ter sido mais humilde.$"

Route126_Text_LeonardoPostBattle:
	.string "Escute me…\n"
	.string "A prática te ajuda a melhorar.\p"
	.string "Você é jovem, entäo näo tenha medo\n"
	.string "em provar e experimentar as coisas."

Route126_Text_IsobelIntro:
	.string "Näo há nada pior quando entra\n"
	.string "água pelo nariz, näo acha?$"

Route126_Text_IsobelDefeat:
	.string "Ah! Por quê…?\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh,Eu engoli muita água!\n"
	.string "Que salgada está!$"

Route126_Text_SiennaIntro:
	.string "Penso em lutar com toda\n"
	.string "minha força!$"

Route126_Text_SiennaDefeat:
	.string "Quanta força tem…?$"

Route126_Text_SiennaPostBattle:
	.string "É, tá na hora de relaxar…\n"
	.string "Vou mergulhar um pouco.$"

Route127_Text_CamdenIntro:
	.string "Vejo bem claro em seu rosto.\n"
	.string "Você quer me desafiar…$"

Route127_Text_CamdenDefeat:
	.string "Como? Aaaah…$"

Route127_Text_CamdenPostBattle:
	.string "Quando um combate tem sido bom,\n"
	.string "fico feliz que dá gosto…$"

Route127_Text_DonnyIntro:
	.string "Você tem um rival a quem você só\n"
	.string "odeia perder contra?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "Eu odeio perder!$"

Route127_Text_DonnyPostBattle:
	.string "Se você tem um rival, näo fica\n"
	.string "com a sensaçäo de que você\l"
	.string "tem que ficar bem melhor?$"

Route127_Text_JonahIntro:
	.string "Pescar me traz uma paz e uma\n"
	.string "serenidade absolutamente incrível…\p"
	.string "Veja, permita-me eu demonstrar…$"

Route127_Text_JonahDefeat:
	.string "Eu perdi, mas sigo täo\n"
	.string " 'ZEN' como sempre…$"

Route127_Text_JonahPostBattle:
	.string "Näo me importa nada se pesco algo\n"
	.string "ou näo, eu sempre sigo tentando…$"

Route127_Text_HenryIntro:
	.string "Näo me diga que pescou um\n"
	.string "Pokémon que sabe surfar?$"

Route127_Text_HenryDefeat:
	.string "Ah! Eu desisto!$"

Route127_Text_HenryPostBattle:
	.string "Seus Pokémon säo fortes.\n"
	.string "Queria pescar uns assim…$"

Route127_Text_RogerIntro:
	.string "Eh, você! Será uma luta entre um fä\n"
	.string "dos Pokémon e um ótimo pescador!$"

Route127_Text_RogerDefeat:
	.string "Näo! A minha linha enrolou!\n"
	.string "A festa acabou!$"

Route127_Text_RogerPostBattle:
	.string "Minha linha de pesca começou a dancar!\n"
	.string "A dança do enrola! Hahaha!$"

Route127_Text_AidanIntro:
	.string "Pokémon Pássaros säo capazes de ver\n"
	.string "suas presas em grandes alturas.$"

Route127_Text_AidanDefeat:
	.string "Ufa… Eu desisto.$"

Route127_Text_AidanPostBattle:
	.string "Há muitos pontos de mergulho\n"
	.string "no mar por aqui.\p"
	.string "Se reconhece rápido pela cor da água,\n"
	.string "que é mais mais escura que o resto.$"

Route127_Text_KojiIntro:
	.string "Correr sem tênis, deixará os pés\n"
	.string "duro igual a granito!$"

Route127_Text_KojiDefeat:
	.string "Ai! Entrou uma pedra\n"
	.string "entre meus dedos!$"

Route127_Text_KojiPostBattle:
	.string "Gosto de andar descalço, mas seu\n"
	.string "Running Shoes säo bem legais.$"

Route127_Text_KojiRegister:
	.string "Isso é o que faço com os que me!\n"
	.string "derrota! Espero te ver novamente.$"

Route127_Text_KojiRematchIntro:
	.string "Corro descalço diariamente. Por\n"
	.string "isso minhas solas säo täo duras.!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch!\n"
	.string "Essas pedras nos meus pés…$"

Route127_Text_KojiPostRematch:
	.string "Quer ficar descalço por um tempo\n"
	.string "para que eu possa usar seus sapatos?$"

Route127_Text_AthenaIntro:
	.string "Deveríamos lutar de forma\n"
	.string "metódica e lenta.$"

Route127_Text_AthenaDefeat:
	.string "Você näo me deu a chance de\n"
	.string "fazer nenhuma estratégia.$"

Route127_Text_AthenaPostBattle:
	.string "Quando fico cercada pelo mar e o céu,\n"
	.string "sinto que o tempo fica mais lento.$"

Route128_Text_IsaiahIntro:
	.string "A Ever Grande City é um caminho\n"
	.string "bem distante… $"

Route128_Text_IsaiahDefeat:
	.string "Minha primeira vitória parece\n"
	.string "estar longe…$"

Route128_Text_IsaiahPostBattle:
	.string "Minha vida inteira foi só perda,\n"
	.string "mas eu nunca vou desistir!$"

Route128_Text_IsaiahRegister:
	.string "Agora sou um desastre, mas sei\n"
	.string "que algum dia poderei ganhar.\p"
	.string "Certo, registre-me na Pokénav.$"

Route128_Text_IsaiahRematchIntro:
	.string "Me sinto muito bem. Vou continuar\n"
	.string "nadando até a Ever Grande City.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Sigo sem saber o gosto da vitória…$"

Route128_Text_IsaiahPostRematch:
	.string "Algum dia chegarei a Ever Grande City\n"
	.string "e entäo certamente eu ganharei…$"

Route128_Text_KatelynIntro:
	.string "Em um triatlo tem que nadar,\n"
	.string "andar de bike, e ainda correr…\p"
	.string "Se trata de uma feroz maratona\n"
	.string "que combina 3 provas.$"

Route128_Text_KatelynDefeat:
	.string "A batalha Pokémon\n"
	.string "também é feroz…$"

Route128_Text_KatelynPostBattle:
	.string "Agora tenho que andar de bicileta,\n"
	.string "mas estou prestes a desistir…$"

Route128_Text_KatelynRegister:
	.string "É melhor ver o lado positivo de tudo\n"
	.string "isso. Quero uma revanche depois.$"

Route128_Text_KatelynRematchIntro:
	.string "O triatlo é longo, mas acho que\n"
	.string "a estrada para se tornar campeäo\l"
	.string "Pokémon seja mais longa e cansativa.$"

Route128_Text_KatelynRematchDefeat:
	.string "Batalhas Pokémon realmente\n"
	.string "säo duras e implacáveis.$"

Route128_Text_KatelynPostRematch:
	.string "Você deveria corgitar a possibilidade\n"
	.string "em aceitas os desafios da Victory Road.$"

Route128_Text_AlexaIntro:
	.string "Trabalhamos duro para montar\n"
	.string "um time para liga Pokémon…\p"
	.string "Näo podemos perder agora!$"

Route128_Text_AlexaDefeat:
	.string "Como isso foi acontecer?!$"

Route128_Text_AlexaPostBattle:
	.string "Depois de tudo que fiz para chegar\n"
	.string "até aqui, näo penso em desistir.$"

Route128_Text_RubenIntro:
	.string "Näo há Treinador mais forte que eu!$"

Route128_Text_RubenDefeat:
	.string "Näo pode ser!$"

Route128_Text_RubenPostBattle:
	.string "Veja… Näo há treinador\n"
	.string "mais forte do que você!$"

Route128_Text_WayneIntro:
	.string "Quero visitar a Ever Grande City,\n"
	.string "entäo peguei um Pokémon que sabe\l"
	.string "Waterfall para subir a queda d'água.$"

Route128_Text_WayneDefeat:
	.string "Tô desanimado!$"

Route128_Text_WaynePostBattle:
	.string "Aaaaai, Por quê?\p"
	.string "Meu Pokémon sabe Waterfall, mas\n"
	.string "näo tenho a insignia de Sootopolis.$"

Route128_Text_HarrisonIntro:
	.string "Você quer lutar?\n"
	.string "Eu me pergunto se eu posso ganhar?$"

Route128_Text_HarrisonDefeat:
	.string "Au!\n"
	.string "Suponho que ganhar era impossível.$"

Route128_Text_HarrisonPostBattle:
	.string "Há um monte de treinadores fortes\n"
	.string "lá na Ever Grande City.\p"
	.string "Você acha que näo mereço estar aqui?$"

Route128_Text_CarleeIntro:
	.string "O sol brilha com muita força\n"
	.string "aqui nesta área.$"

Route128_Text_CarleeDefeat:
	.string "Eu näo consegui ver bem por\n"
	.string "causa do brilho do sol.$"

Route128_Text_CarleePostBattle:
	.string "Voltarei pra casa…\n"
	.string "Preciso reaplicar o protetor solar.$"

Route129_Text_ChaseIntro:
	.string "Oh! É o meu primeiro triatlo.\n"
	.string "Estou tenso e nervoso…$"

Route129_Text_ChaseDefeat:
	.string "Buaaaaaaaaa!!\n"
	.string "Eu näo ganhei!$"

Route129_Text_ChasePostBattle:
	.string "Estou täo tenso que näo serei\n"
	.string "capaz de dar tudo de mim…$"

Route129_Text_AllisonIntro:
	.string "Estou no meio de um triathlon, mas\n"
	.string "posso para e lutar um pouco…$"

Route129_Text_AllisonDefeat:
	.string "Achei que ganharia!$"

Route129_Text_AllisonPostBattle:
	.string "Sabe o que é mais legal nos triathlons?\n"
	.string "Saber que deve ir até o limite de\p"
	.string "sua força e da sua resistência\n"
	.string "contra o vento e mar!$"

Route129_Text_ReedIntro:
	.string "Ei, você!\n"
	.string "Vamos direto ao assunto!$"

Route129_Text_ReedDefeat:
	.string "Fui täo fácil assim.\n"
	.string "Que derrota!$"

Route129_Text_ReedPostBattle:
	.string "Pra que perder tempo.\n"
	.string "Vou para casa e esquecer de tudo!$"

Route129_Text_TishaIntro:
	.string "Qual é a pressa?\n"
	.string "Vamos devagar é com calma…$"

Route129_Text_TishaDefeat:
	.string "Oh…!\n"
	.string "Eu queria descansar um pouco mais…$"

Route129_Text_TishaPostBattle:
	.string "Näo odeia quando faz as coisas\n"
	.string "depressa e mal?\p"
	.string "É por isso tento levar\n"
	.string "meu tempo lentamente.$"

Route129_Text_ClarenceIntro:
	.string "Surfar näo é täo fácil como\n"
	.string "parece, näo é mesmo?$"

Route129_Text_ClarenceDefeat:
	.string "Ganhar isso näo é fácil.$"

Route129_Text_ClarencePostBattle:
	.string "Se planeja chegar na liga Pokémon?\n"
	.string "Entäo muita sorte!$"

Route130_Text_RodneyIntro:
	.string "Que surpresa! Eu näo esperava\n"
	.string "ver um Treinador aqui no mar.\p"
	.string "Bem, lutaremos para celebrar!$"

Route130_Text_RodneyDefeat:
	.string "Uf… É forte, eu acredito…$"

Route130_Text_RodneyPostBattle:
	.string "Seus olhos tem o brilho daqueles\n"
	.string "que estäo acostumados a aceitar\l"
	.string "desafios e ganha. Está indo bem!$"

Route130_Text_KatieIntro:
	.string "Meu coraçäo acalma quando\n"
	.string "flutuo entre as suaves\l"
	.string "ondas desse lindo mar…$"

Route130_Text_KatieDefeat:
	.string "A amplitude dessa minha derrota\n"
	.string "se perde no infinito do horizonte…$"

Route130_Text_KatiePostBattle:
	.string "Todas as crianças do mundo sonham\n"
	.string "em tornar-se campeäo Pokémon.$"

Route130_Text_SantiagoIntro:
	.string "Ficar boiando assim no mar…\n"
	.string "É estar em paz total.$"

Route130_Text_SantiagoDefeat:
	.string "Por que você veio tirar a minha paz?$"

Route130_Text_SantiagoPostBattle:
	.string "Nadar, lutar; lutar, nadar.\n"
	.string "Näo sei qual gosto mais…$"

Route131_Text_RichardIntro:
	.string "O mar está repleto de Pokémon.\n"
	.string "Näo é fácil nadar aqui, eu lhe digo.$"

Route131_Text_RichardDefeat:
	.string "Pokémon treinado por treinador\n"
	.string "säo mais fortes…$"

Route131_Text_RichardPostBattle:
	.string "Uf… Uf… Estou cansado…\n"
	.string "A ida foi bem fácil, mas a volta…\l"
	.string "essa é a parte mais difícil.\n"
	.string "Terei força para chegar em\p"
	.string "segurança até a costa?$"

Route131_Text_HermanIntro:
	.string "O mar… A mar… O mar…\n"
	.string "O mar é täo grande que aborrece!\l"
	.string "E eu estou até doente e cansado do mar!$"

Route131_Text_HermanDefeat:
	.string "Näooo!$"

Route131_Text_HermanPostBattle:
	.string "Que tédio, mas devo seguir…\p"
	.string "Sou um nadador nato!\n"
	.string "Näo sei fazer outra coisa!$"

Route131_Text_SusieIntro:
	.string "Olá, olá, olá…!\n"
	.string "Que tal um combate, você e eu?$"

Route131_Text_SusieDefeat:
	.string "Quanta garra, apesar de sua aparência!$"

Route131_Text_SusiePostBattle:
	.string "Você viu um cara que näo para\n"
	.string "de choraminga o tempo todo?\p"
	.string "É tudo conversa. Na realidade\n"
	.string "gosta do mar mais do que nós 2.$"

Route131_Text_KaraIntro:
	.string "Por que homens amam\p"
	.string "tanto ver bikini?$"

Route131_Text_KaraDefeat:
	.string "Eu vou embora daqui!$"

Route131_Text_KaraPostBattle:
	.string "Talvez os olhares näo seja para meu\n"
	.string "bikini. Sim, deve ser a minha beleza!$"

Route131_Text_ReliIntro:
	.string "Reli: Vamos batalhar juntos\n"
	.string "como irmäos para ganhar!$"

Route131_Text_ReliDefeat:
	.string "Reli: Näo tivemos sucesso mesmo\n"
	.string "trabalhando juntos…$"

Route131_Text_ReliPostBattle:
	.string "Reli: Todo o povo de Pacifidlog vive\n"
	.string "por e para o mar e os Pokémon desde\l"
	.string "o momento em que nascem.$"

Route131_Text_ReliNotEnoughMons:
	.string "Reli: Ei! Näo tem 2 Pokémon?\n"
	.string "Pois entäo näo podemos batalhar…$"

Route131_Text_IanIntro:
	.string "Ian: Faço o meu melhor junto\n"
	.string "com minha irmä.$"

Route131_Text_IanDefeat:
	.string "Ian: Poxa… Eu fiz o meu melhor,\n"
	.string "mas ainda assim perdemos…$"

Route131_Text_IanPostBattle:
	.string "Ian: Sabia que Pacifidlog\n"
	.string "está flutuando?\p"
	.string "Por isso tudo que considere como\n"
	.string "mar, é parte de Pacifidlog!$"

Route131_Text_IanNotEnoughMons:
	.string "Ian: Se você tiver 2 Pokémon,\n"
	.string "lutaremos contigo!$"

Route131_Text_TaliaIntro:
	.string "Se ganhar, dou uma informaçäo\n"
	.string "que vale seu peso em ouro!$"

Route131_Text_TaliaDefeat:
	.string "Que??\n"
	.string "Eu perdi?!$"

Route131_Text_TaliaPostBattle:
	.string "Por perto há um lugar estranho.\n"
	.string "Lá há uma torre gigantesca.\l"
	.string "Por que näo faz uma visita?$"

Route131_Text_KevinIntro:
	.string "O povo de Pacifidlog\n"
	.string "säo muito pacíficos.\p"
	.string "Nunca ficam com raiva.\n"
	.string "Isso vale para mim também!$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Bah! Oh, no momento…\n"
	.string "Näo estou com raiva, é sério!\p"
	.string "Mas, você é bem forte!$"

Route132_Text_GilbertIntro:
	.string "Quando era criança, me resfriava\n"
	.string "muito, mas desde que eu começei\l"
	.string "a nadar, näo acontece mais.$"

Route132_Text_GilbertDefeat:
	.string "Queria é ser forte…$"

Route132_Text_GilbertPostBattle:
	.string "Os treinadores viajam por campos\n"
	.string "e montanhas. Devem estar em forma.$"

Route132_Text_DanaIntro:
	.string "Nunca nado em lugares onde\n"
	.string "a maré está muito forte.$"

Route132_Text_DanaDefeat:
	.string "Foi täo rápido!$"

Route132_Text_DanaPostBattle:
	.string "Se essa maré me levar, acho que\n"
	.string "ficaria perdida aqui…$"

Route132_Text_RonaldIntro:
	.string "Vencer ou perder, nunca saberá\n"
	.string "se näo tentar!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "Afundei na derrota!$"

Route132_Text_RonaldPostBattle:
	.string "Eu nunca luto se tenho certeza que\n"
	.string "vou ganhar. Eu gosto mesmo é de\l"
	.string "sentir a emoçäo da incerteza…$"

Route132_Text_KiyoIntro:
	.string "Estou com meus Pokémon 24 horas\n"
	.string "por dia. Como pretende me derrotar?$"

Route132_Text_KiyoDefeat:
	.string "Eu perdi?\n"
	.string "Que ridículo eu fui…$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "Você é um fä dos Pokémon, eh?\p"
	.string "Você deve passar cada segundo do dia\n"
	.string "com seus Pokémon, näo é?$"

Route132_Text_MakaylaIntro:
	.string "Sempre luto com o meu marido,\n"
	.string "mas posso vencer até sem ele.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, parece que uniäo faz a força.$"

Route132_Text_MakaylaPostBattle:
	.string "Hihihihi… O jovem ali é idéntico\n"
	.string "ao meu marido quando era jovem.\p"
	.string "Ah, como o tempo passa!$"

Route132_Text_JonathanIntro:
	.string "Há alguém que me observa\n"
	.string "atentamente. Era você?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "Que incrível exibiçäo de força!$"

Route132_Text_JonathanPostBattle:
	.string "Esta sensaçäo de que há alguém\n"
	.string "observando é ruim.\p"
	.string "Näo posso me concentrar!$"

Route132_Text_PaxtonIntro:
	.string "Aonde minha esposa pode ter ido?\n"
	.string "Sempre lutamos juntos.\l"
	.string "Me pergunto se sozinho eu ganho.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, eu vejo que näo consigo chegar\n"
	.string "a nenhuma parte sozinho.$"

Route132_Text_PaxtonPostBattle:
	.string "É certo que minha esposa estar me\n"
	.string "procurando. Quero encontrá-la.$"

Route132_Text_DarcyIntro:
	.string "Eu gosto muito de treinar aqui sozinha.\n"
	.string "Por que tem vindo tanta gente?$"

Route132_Text_DarcyDefeat:
	.string "Certo! Eu näo vou reclamar das\n"
	.string "pessoas estarem aqui.$"

Route132_Text_DarcyPostBattle:
	.string "Eu vou fazer parceria com aquele\n"
	.string "senhor e desafiar outras equipes.$"

Route133_Text_FranklinIntro:
	.string "Foi arrastado pela corrente até aqui?\n"
	.string "Deve ser seu destino. Vamos batalhar!$"

Route133_Text_FranklinDefeat:
	.string "Uau!\n"
	.string "É muito forte!$"

Route133_Text_FranklinPostBattle:
	.string "Logo eu teria que encontrar alguém\n"
	.string "täo forte como você é…\l"
	.string "Devo ter uma maldiçäo…$"

Route133_Text_DebraIntro:
	.string "Eu levo uma vida de miséria e…\n"
	.string "tristeza. Fui trazida até aqui,\l"
	.string "e aqui estou a deriva…$"

Route133_Text_DebraDefeat:
	.string "Outra derrota…$"

Route133_Text_DebraPostBattle:
	.string "Uma vida vaga…\n"
	.string "Acho que näo quero mais!$"

Route133_Text_LindaIntro:
	.string "Olá!\n"
	.string "Eu estava esperando você!$"

Route133_Text_LindaDefeat:
	.string "Näo valeu!$"

Route133_Text_LindaPostBattle:
	.string "Alguém täo jovem e täo forte…\n"
	.string "Isso é chato!$"

Route133_Text_WarrenIntro:
	.string "Gosto de nadar como todo mundo, mas\n"
	.string "sou o mais original treinador Pokémon.$"

Route133_Text_WarrenDefeat:
	.string "Droga!\n"
	.string "Estou num caminho sem saída!$"

Route133_Text_WarrenPostBattle:
	.string "É muito mais original fazer as coisas\n"
	.string "a seu modo do que como todo mundo.\l"
	.string "Hehehehe, como isso é óbvio!$"

Route133_Text_BeckIntro:
	.string "Eu cheguei até aqui com ajuda\n"
	.string "do meu Pokémon pássaro.$"

Route133_Text_BeckDefeat:
	.string "Seu estilo…\n"
	.string "é super legal!$"

Route133_Text_BeckPostBattle:
	.string "Queria voltar para Fortree, mas eu\n"
	.string "tenho carinho a este lugar, também.$"

Route133_Text_MollieIntro:
	.string "Eu já batalhei aqui muitas vezes\n"
	.string "que eu perdi a conta.$"

Route133_Text_MollieDefeat:
	.string "Posso ter perdido milhares de vezes,\n"
	.string "mas uma perda machuca…$"

Route133_Text_MolliePostBattle:
	.string "Siga assim jovem. Algum dia será\n"
	.string "täo notável como meu marido e eu.$"

Route133_Text_ConorIntro:
	.string "Os jovens sempre se deixam levar. Nem\n"
	.string "planejam nem seguem um rumo preciso.$"

Route133_Text_ConorDefeat:
	.string "Hum… Você tem um firme propósito.$"

Route133_Text_ConorPostBattle:
	.string "Näo se deixe influenciar pelos outros.\n"
	.string "Se concentre em suas convicçöes.$"

Route134_Text_JackIntro:
	.string "Até mesmo os Pokémon que näo sabem\n"
	.string "nadar säo arrastados pela correnteza.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Acho que os Pokémon gostam da maré\n"
	.string "rápida, mas säo muito perigosas…$"

Route134_Text_LaurelIntro:
	.string "Meus Luvdisc procuram um rival\n"
	.string "divertido. Será você?…$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "Há um colecionador procurando\n"
	.string "por escamas de Luvdisc.$"

Route134_Text_AlexIntro:
	.string "Ei você ai! Chega de descanso, certo!\n"
	.string "É hora de um combate!$"

Route134_Text_AlexDefeat:
	.string "Eu perdi de novo…$"

Route134_Text_AlexPostBattle:
	.string "Meu Pokémon pássaro ficou cansado\n"
	.string "depois de um longo vôo…$"

Route134_Text_HitoshiIntro:
	.string "Você é Treinador Pokémon?\n"
	.string "Näo precisa dizer. Vamos lutar.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Fui eu que te desafiei, e ainda perdi.\n"
	.string "Estou muito envergonhado…$"

Route134_Text_AaronIntro:
	.string "A força da maré desta área te\n"
	.string "ajuda a ser cada vez mais forte.$"

Route134_Text_AaronDefeat:
	.string "Sim, já sei, eu perdi feio.$"

Route134_Text_AaronPostBattle:
	.string "Iremos treinar mais a sério\n"
	.string "no Meteor Falls.\p"
	.string "Se quiser também será bem vindo.\n"
	.string "É certo que isso te fará mais forte!$"

Route134_Text_KelvinIntro:
	.string "O nosso barco!\n"
	.string "Foi levado pela maré!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Para, para, por favor!$"

Route134_Text_KelvinPostBattle:
	.string "Se näo podemos surfar,\n"
	.string "como vamos chegar em casa?\p"
	.string "Acho que um Pokémon desmaiado ainda\n"
	.string "pode surfar, mas parece um abuso.$"

Route134_Text_MarleyIntro:
	.string "Acha que seus Pokémon pode\n"
	.string "evitar um ataque veloz?$"

Route134_Text_MarleyDefeat:
	.string "Tem usado uma técnica desconhecida\n"
	.string "para mim! Minha derrota foi total.$"

Route134_Text_MarleyPostBattle:
	.string "Estou apaixonada pela velocidade.\n"
	.string "Quero treinar muito.$"

Route134_Text_ReynaIntro:
	.string "Meu Pokémon näo será\n"
	.string "derrotado fácilmente!$"

Route134_Text_ReynaDefeat:
	.string "Que? Como?\n"
	.string "Explique como eu perdi!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "Você ganhou, tudo bem!\p"
	.string "Vou fazer meu caminho de volta\n"
	.string "batalhando com quem encontrar!$"

Route134_Text_HudsonIntro:
	.string "Diga-me, tem visto algum outro\n"
	.string "Marinheiro por ai?$"

Route134_Text_HudsonDefeat:
	.string "Ok, você näo viu nada…$"

Route134_Text_HudsonPostBattle:
	.string "A maré levou o nosso barco.\p"
	.string "Meu companheiro é tímido,\n"
	.string "por isso estou preocupado.$"
